window.verbosIrregulares_VI = {

    VI1: [
        { tipo: "VI", eng: "BE", past: "WAS/WERE", part: "BEEN", esp: "SER O ESTAR" },
        { tipo: "VI", eng: "GO", past: "WENT", part: "GONE", esp: "IR" },
        { tipo: "VI", eng: "EAT", past: "ATE", part: "EATEN", esp: "COMER" },
        { tipo: "VI", eng: "DRINK", past: "DRANK", part: "DRUNK", esp: "BEBER" },
        { tipo: "VI", eng: "HAVE", past: "HAD", part: "HAD", esp: "TENER" },
        { tipo: "VI", eng: "DO", past: "DID", part: "DONE", esp: "HACER" },
        { tipo: "VI", eng: "SAY", past: "SAID", part: "SAID", esp: "DECIR" },
        { tipo: "VI", eng: "SEE", past: "SAW", part: "SEEN", esp: "VER" },
        { tipo: "VI", eng: "TAKE", past: "TOOK", part: "TAKEN", esp: "TOMAR" },
        { tipo: "VI", eng: "FIND", past: "FOUND", part: "FOUND", esp: "ENCONTRAR" },
        { tipo: "VI", eng: "COME", past: "CAME", part: "COME", esp: "VENIR" },
        { tipo: "VI", eng: "KNOW", past: "KNEW", part: "KNOWN", esp: "SABER" },
        { tipo: "VI", eng: "GET", past: "GOT", part: "GOTTEN", esp: "OBTENER" },
        { tipo: "VI", eng: "GIVE", past: "GAVE", part: "GIVEN", esp: "DAR" },
        { tipo: "VI", eng: "BECOME", past: "BECAME", part: "BECOME", esp: "LLEGAR A SER" },
        { tipo: "VI", eng: "FEEL", past: "FELT", part: "FELT", esp: "SENTIR" },
        { tipo: "VI", eng: "LEAVE", past: "LEFT", part: "LEFT", esp: "SALIR O DEJAR" },
        { tipo: "VI", eng: "PUT", past: "PUT", part: "PUT", esp: "PONER" },
        { tipo: "VI", eng: "MEAN", past: "MEANT", part: "MEANT", esp: "SIGNIFICAR" },
        { tipo: "VI", eng: "KEEP", past: "KEPT", part: "KEPT", esp: "MANTENER" },

    ],
    VI2:[
        { tipo: "VI", eng: "LET", past: "LET", part: "LET", esp: "PERMITIR" },
        { tipo: "VI", eng: "BEGIN", past: "BEGAN", part: "BEGUN", esp: "EMPEZAR" },
        { tipo: "VI", eng: "HEAR", past: "HEARD", part: "HEARD", esp: "OÍR" },
        { tipo: "VI", eng: "RUN", past: "RAN", part: "RUN", esp: "CORRER" },
        { tipo: "VI", eng: "BRING", past: "BROUGHT", part: "BROUGHT", esp: "TRAER" },
        { tipo: "VI", eng: "WRITE", past: "WROTE", part: "WRITTEN", esp: "ESCRIBIR" },
        { tipo: "VI", eng: "SIT", past: "SAT", part: "SAT", esp: "SENTARSE" },
        { tipo: "VI", eng: "STAND", past: "STOOD", part: "STOOD", esp: "ESTAR DE PIE" },
        { tipo: "VI", eng: "LOSE", past: "LOST", part: "LOST", esp: "PERDER" },
        { tipo: "VI", eng: "PAY", past: "PAID", part: "PAID", esp: "PAGAR" },
        { tipo: "VI", eng: "MEET", past: "MET", part: "MET", esp: "CONOCER O REUNIRSE" },
        { tipo: "VI", eng: "SET", past: "SET", part: "SET", esp: "ESTABLECER" },
        { tipo: "VI", eng: "LEARN", past: "LEARNT", part: "LEARNT", esp: "APRENDER" },
        { tipo: "VI", eng: "CHOOSE", past: "CHOSE", part: "CHOSEN", esp: "ELEGIR" },
        { tipo: "VI", eng: "SPEAK", past: "SPOKE", part: "SPOKEN", esp: "HABLAR" },
        { tipo: "VI", eng: "SLEEP", past: "SLEPT", part: "SLEPT", esp: "DORMIR" },
        { tipo: "VI", eng: "WAKE", past: "WOKE", part: "WOKEN", esp: "DESPERTAR" },
        { tipo: "VI", eng: "WIN", past: "WON", part: "WON", esp: "GANAR" },
        { tipo: "VI", eng: "BUY", past: "BOUGHT", part: "BOUGHT", esp: "COMPRAR" },
        { tipo: "VI", eng: "SEND", past: "SENT", part: "SENT", esp: "ENVIAR" }
    ],
    VI3: [
        
        { tipo: "VI", eng: "READ", past: "READ", part: "READ", esp: "LEER" },
        { tipo: "VI", eng: "SELL", past: "SOLD", part: "SOLD", esp: "VENDER" },
        { tipo: "VI", eng: "BREAK", past: "BROKE", part: "BROKEN", esp: "ROMPER" },
        { tipo: "VI", eng: "FALL", past: "FELL", part: "FALLEN", esp: "CAER" },
        { tipo: "VI", eng: "CUT", past: "CUT", part: "CUT", esp: "CORTAR" },
        { tipo: "VI", eng: "SING", past: "SANG", part: "SUNG", esp: "CANTAR" },
        { tipo: "VI", eng: "SWIM", past: "SWAM", part: "SWUM", esp: "NADAR" },
        { tipo: "VI", eng: "TELL", past: "TOLD", part: "TOLD", esp: "CONTAR O DECIR" },
        { tipo: "VI", eng: "UNDERSTAND", past: "UNDERSTOOD", part: "UNDERSTOOD", esp: "ENTENDER" },
        { tipo: "VI", eng: "WEAR", past: "WORE", part: "WORN", esp: "VESTIR O LLEVAR PUESTO" },
        { tipo: "VI", eng: "DRIVE", past: "DROVE", part: "DRIVEN", esp: "CONDUCIR" },
        { tipo: "VI", eng: "FORGIVE", past: "FORGAVE", part: "FORGIVEN", esp: "PERDONAR" },
        { tipo: "VI", eng: "GROW", past: "GREW", part: "GROWN", esp: "CRECER" },
        { tipo: "VI", eng: "HIT", past: "HIT", part: "HIT", esp: "GOLPEAR" },
        { tipo: "VI", eng: "HOLD", past: "HELD", part: "HELD", esp: "SOSTENER/AFERRAR" },
        { tipo: "VI", eng: "HURT", past: "HURT", part: "HURT", esp: "HERIR O DOLER" },
        { tipo: "VI", eng: "KEEP", past: "KEPT", part: "KEPT", esp: "GUARDAR" },
        { tipo: "VI", eng: "LAY", past: "LAID", part: "LAID", esp: "EXTENDER O PONER" },
        { tipo: "VI", eng: "LEAD", past: "LED", part: "LED", esp: "GUIAR" }
    ],
    VI4: [
        { tipo: "VI", eng: "LEND", past: "LENT", part: "LENT", esp: "PRESTAR" },
        { tipo: "VI", eng: "LIE", past: "LAY", part: "LAIN", esp: "TUMBARSE" },
        { tipo: "VI", eng: "LIGHT", past: "LIT", part: "LIT", esp: "ENCENDER" },
        { tipo: "VI", eng: "MAKE", past: "MADE", part: "MADE", esp: "HACER O FABRICAR" },
        { tipo: "VI", eng: "RIDE", past: "RODE", part: "RIDDEN", esp: "MONTAR (BICI/CABALLO)" },
        { tipo: "VI", eng: "RING", past: "RANG", part: "RUNG", esp: "LLAMAR (TIMBRE)" },
        { tipo: "VI", eng: "RISE", past: "ROSE", part: "RISEN", esp: "SUBIR O LEVANTARSE" },
        { tipo: "VI", eng: "SHAKE", past: "SHOOK", part: "SHAKEN", esp: "AGITAR" },
        { tipo: "VI", eng: "SHINE", past: "SHONE", part: "SHONE", esp: "BRILLAR" },
        { tipo: "VI", eng: "SHOOT", past: "SHOT", part: "SHOT", esp: "DISPARAR" },
        { tipo: "VI", eng: "SHUT", past: "SHUT", part: "SHUT", esp: "CERRAR" },
        { tipo: "VI", eng: "SPEND", past: "SPENT", part: "SPENT", esp: "GASTAR" },
        { tipo: "VI", eng: "STEAL", past: "STOLE", part: "STOLEN", esp: "ROBAR" },
        { tipo: "VI", eng: "STICK", past: "STUCK", part: "STUCK", esp: "PEGAR O ADHERIR" },
        { tipo: "VI", eng: "STRIKE", past: "STRUCK", part: "STRUCK", esp: "GOLPEAR" },
        { tipo: "VI", eng: "SWEAR", past: "SWORE", part: "SWORN", esp: "JURAR" },
        { tipo: "VI", eng: "TEACH", past: "TAUGHT", part: "TAUGHT", esp: "ENSEÑAR" },
        { tipo: "VI", eng: "TEAR", past: "TORE", part: "TORN", esp: "RASGAR" },
        { tipo: "VI", eng: "THINK", past: "THOUGHT", part: "THOUGHT", esp: "PENSAR" },
        { tipo: "VI", eng: "THROW", past: "THREW", part: "THROWN", esp: "LANZAR" }
    ],
    VI5: [
        { tipo: "VI", eng: "WAKE", past: "WOKE", part: "WOKEN", esp: "DESPERTAR" },
        { tipo: "VI", eng: "WIN", past: "WON", part: "WON", esp: "GANAR" },
        { tipo: "VI", eng: "WITHDRAW", past: "WITHDREW", part: "WITHDRAWN", esp: "RETIRAR" },
        { tipo: "VI", eng: "BEND", past: "BENT", part: "BENT", esp: "DOBLAR" },
        { tipo: "VI", eng: "BITE", past: "BIT", part: "BITTEN", esp: "MORDER" },
        { tipo: "VI", eng: "BLEED", past: "BLED", part: "BLED", esp: "SANGRAR" },
        { tipo: "VI", eng: "BLOW", past: "BLEW", part: "BLOWN", esp: "SOPLAR" },
        { tipo: "VI", eng: "BUILD", past: "BUILT", part: "BUILT", esp: "CONSTRUIR" },
        { tipo: "VI", eng: "BURN", past: "BURNT", part: "BURNT", esp: "QUEMAR" },
        { tipo: "VI", eng: "COST", past: "COST", part: "COST", esp: "COSTAR" },
        { tipo: "VI", eng: "DIG", past: "DUG", part: "DUG", esp: "CAVAR" },
        { tipo: "VI", eng: "DREAM", past: "DREAMT", part: "DREAMT", esp: "SOÑAR" },
        { tipo: "VI", eng: "FEED", past: "FED", part: "FED", esp: "ALIMENTAR" },
        { tipo: "VI", eng: "FIGHT", past: "FOUGHT", part: "FOUGHT", esp: "PELEAR" },
        { tipo: "VI", eng: "FLY", past: "FLEW", part: "FLOWN", esp: "VOLAR" },
        { tipo: "VI", eng: "FREEZE", past: "FROZE", part: "FROZEN", esp: "CONGELAR" },
        { tipo: "VI", eng: "HIDE", past: "HID", part: "HIDDEN", esp: "ESCONDER" },
        { tipo: "VI", eng: "KNEEL", past: "KNELT", part: "KNELT", esp: "ARRODILLARSE" },
        { tipo: "VI", eng: "QUIT", past: "QUIT", part: "QUIT", esp: "RENUNCIAR O PARAR" },
        { tipo: "VI", eng: "SMELL", past: "SMELT", part: "SMELT", esp: "OLER" }
    ],
    VI6: [
        { tipo: "VI", eng: "BET", past: "BET", part: "BET", esp: "APOSTAR" },
        { tipo: "VI", eng: "REACH", past: "REACHED", part: "REACHED", esp: "ALCANZAR" },
        { tipo: "VI", eng: "SHINE", past: "SHONE", part: "SHONE", esp: "BRILLAR" },
        { tipo: "VI", eng: "SEEK", past: "SOUGHT", part: "SOUGHT", esp: "INDAGAR" },
        { tipo: "VI", eng: "UNDERSTAND", past: "UNDERSTOOD", part: "UNDERSTOOD", esp: "COMPRENDER" },
        { tipo: "VI", eng: "SING", past: "SANG", part: "SUNG", esp: "CANTAR" },
        { tipo: "VI", eng: "SHUT", past: "SHUT", part: "SHUT", esp: "CALLAR/CERRAR" },
        { tipo: "VI", eng: "BE", past: "WAS/WERE", part: "BEEN", esp: "SER/ESTAR" },
        { tipo: "VI", eng: "HAVE", past: "HAD", part: "HAD", esp: "TENER" },
        { tipo: "VI", eng: "DO", past: "DID", part: "DONE", esp: "HACER" },
        { tipo: "VI", eng: "SAY", past: "SAID", part: "SAID", esp: "DECIR" },
        { tipo: "VI", eng: "GO", past: "WENT", part: "GONE", esp: "IR" },
        { tipo: "VI", eng: "GET", past: "GOT", part: "GOT/GOTTEN", esp: "OBTENER" },
        { tipo: "VI", eng: "MAKE", past: "MADE", part: "MADE", esp: "HACER/CONSTRUIR" },
        { tipo: "VI", eng: "KNOW", past: "KNEW", part: "KNOWN", esp: "SABER/CONOCER" },
        { tipo: "VI", eng: "THINK", past: "THOUGHT", part: "THOUGHT", esp: "PENSAR" },
        { tipo: "VI", eng: "TAKE", past: "TOOK", part: "TAKEN", esp: "TOMAR/LLEVAR" },
        { tipo: "VI", eng: "SEE", past: "SAW", part: "SEEN", esp: "VER" },
        { tipo: "VI", eng: "COME", past: "CAME", part: "COME", esp: "VENIR" },
        { tipo: "VI", eng: "FIND", past: "FOUND", part: "FOUND", esp: "ENCONTRAR" }
        

    ],
    VI7: [
        { tipo: "VI", eng: "GIVE", past: "GAVE", part: "GIVEN", esp: "DAR" },
        { tipo: "VI", eng: "TELL", past: "TOLD", part: "TOLD", esp: "DECIR/HABLAR" },
        { tipo: "VI", eng: "MEAN", past: "MEANT", part: "MEANT", esp: "SIGNIFICAR" },
        { tipo: "VI", eng: "KEEP", past: "KEPT", part: "KEPT", esp: "MANTENER" },
        { tipo: "VI", eng: "LET", past: "LET", part: "LET", esp: "PERMITIR/DEJAR" },
        { tipo: "VI", eng: "FEEL", past: "FELT", part: "FELT", esp: "SENTIR" },
        { tipo: "VI", eng: "BECOME", past: "BECAME", part: "BECOME", esp: "CONVERTIRSE" },
        { tipo: "VI", eng: "RUN", past: "RAN", part: "RUN", esp: "CORRER" },
        { tipo: "VI", eng: "BRING", past: "BROUGHT", part: "BROUGHT", esp: "TRAER" },
        { tipo: "VI", eng: "WRITE", past: "WROTE", part: "WRITTEN", esp: "ESCRIBIR" },
        { tipo: "VI", eng: "READ", past: "READ", part: "READ", esp: "LEER" }, // Se escribe igual, cambia pronunciación
        { tipo: "VI", eng: "SIT", past: "SAT", part: "SAT", esp: "SENTARSE" },
        { tipo: "VI", eng: "STAND", past: "STOOD", part: "STOOD", esp: "PARARSE/ESTAR DE PIE" },
        { tipo: "VI", eng: "PAY", past: "PAID", part: "PAID", esp: "PAGAR" },
        { tipo: "VI", eng: "BUY", past: "BOUGHT", part: "BOUGHT", esp: "COMPRAR" },
        { tipo: "VI", eng: "BEGIN", past: "BEGAN", part: "BEGUN", esp: "EMPEZAR" },
        { tipo: "VI", eng: "HEAR", past: "HEARD", part: "HEARD", esp: "OÍR" },
        { tipo: "VI",  eng: "CHOOSE", past: "CHOSE", part: "CHOSEN", esp: "ELEGIR" },
        { tipo: "VI",  eng: "SLEEP", past: "SLEPT", part: "SLEPT", esp: "DORMIR" },
        { tipo: "VI",  eng: "WAKE UP", past: "WOKE UP", part: "WOKEN UP", esp: "DESPERTAR" },
    ],
    VI8: [
        { tipo: "VI",  eng: "DRINK", past: "DRANK", part: "DRUNK", esp: "BEBER" },
        { tipo: "VI",  eng: "BREAK", past: "BROKE", part: "BROKEN", esp: "ROMPER" },
        { tipo: "VI",  eng: "WEAR", past: "WORE", part: "WORN", esp: "LLEVAR PUESTO" },
        { tipo: "VI",  eng: "UNDERSTAND", past: "UNDERSTOOD", part: "UNDERSTOOD", esp: "ENTENDER" },        
        { tipo: "VI",  eng: "LEARN", past: "LEARNT/LEARNED", part: "LEARNT/LEARNED", esp: "APRENDER" },
        { tipo: "VI",  eng: "TEACH", past: "TAUGHT", part: "TAUGHT", esp: "ENSEÑAR" },
        { tipo: "VI",  eng: "LOSE", past: "LOST", part: "LOST", esp: "PERDER" },
        { tipo: "VI",  eng: "WIN", past: "WON", part: "WON", esp: "GANAR" },
        { tipo: "VI",  eng: "SPEND", past: "SPENT", part: "SPENT", esp: "GASTAR" },
        { tipo: "VI", eng: "FORGET", past: "FORGOT", part: "FORGOTTEN", esp: "OLVIDAR" },
        { tipo: "VI", eng: "SPIT", past: "SPIT/SPAT", part: "SPIT/SPAT", esp: "ESCUPIR" },
        { tipo: "VI", eng: "SEND", past: "SENT", part: "SENT", esp: "ENVIAR" },
        { tipo: "VI", eng: "GROW", past: "GREW", part: "GROWN", esp: "CRECER" },
        { tipo: "VI", eng: "THRIVE", past: "THROVE/THRIVED", part: "THRIVEN/THRIVED", esp: "PROSPERAR" },
        { tipo: "VI",  eng: "THROW", past: "THREW", part: "THROWN", esp: "LANZAR" },
        { tipo: "VI",  eng: "CATCH", past: "CAUGHT", part: "CAUGHT", esp: "ATRAPAR" },
        { tipo: "VI",  eng: "DRAW", past: "DREW", part: "DRAWN", esp: "DIBUJAR" },
        { tipo: "VI",  eng: "DRIVE", past: "DROVE", part: "DRIVEN", esp: "CONDUCIR" },
        { tipo: "VI",  eng: "FLY", past: "FLEW", part: "FLOWN", esp: "VOLAR" },
        { tipo: "VI",  eng: "SWIM", past: "SWAM", part: "SWUM", esp: "NADAR" },
    ],
    VI9: [
        { tipo: "VI",  eng: "HIT", past: "HIT", part: "HIT", esp: "GOLPEAR" },
        { tipo: "VI", eng: "STEAL", past: "STOLE", part: "STOLEN", esp: "ROBAR" },
        { tipo: "VI", eng: "TEACH", past: "TAUGHT", part: "TAUGHT", esp: "ENSEÑAR" },
        { tipo: "VI", eng: "GO", past: "WENT", part: "GONE", esp: "IR" },
        { tipo: "VI", eng: "EAT", past: "ATE", part: "EATEN", esp: "COMER" },
        { tipo: "VI", eng: "DRINK", past: "DRANK", part: "DRUNK", esp: "BEBER" },
        { tipo: "VI", eng: "SEE", past: "SAW", part: "SEEN", esp: "VER" },
        { tipo: "VI", eng: "DO", past: "DID", part: "DONE", esp: "HACER" },
        { tipo: "VI", eng: "MAKE", past: "MADE", part: "MADE", esp: "HACER/FABRICAR" },
        { tipo: "VI", eng: "TAKE", past: "TOOK", part: "TAKEN", esp: "TOMAR/LLEVAR" },
        { tipo: "VI", eng: "COME", past: "CAME", part: "COME", esp: "VENIR" },
        { tipo: "VI", eng: "KNOW", past: "KNEW", part: "KNOWN", esp: "SABER/CONOCER" },
        { tipo: "VI", eng: "GIVE", past: "GAVE", part: "GIVEN", esp: "DAR" },
        { tipo: "VI", eng: "FIND", past: "FOUND", part: "FOUND", esp: "ENCONTRAR" },
        { tipo: "VI", eng: "BUY", past: "BOUGHT", part: "BOUGHT", esp: "COMPRAR" },
        { tipo: "VI", eng: "SLEEP", past: "SLEPT", part: "SLEPT", esp: "DORMIR" },
        { tipo: "VI", eng: "SPEAK", past: "SPOKE", part: "SPOKEN", esp: "HABLAR" },
        { tipo: "VI", eng: "WRITE", past: "WROTE", part: "WRITTEN", esp: "ESCRIBIR" },
        { tipo: "VI", eng: "READ", past: "READ", part: "READ", esp: "LEER" },
        { tipo: "VI", eng: "RUN", past: "RAN", part: "RUN", esp: "CORRER" },
    ],
    VI10: [

        {tipo:  "VI",  eng:  "TEAR",  past:  "TORE",  part:  "TORN",  esp:  "DESGARRAR"},
        {tipo:  "VI",  eng:  "LEAVE",  past:  "LEFT",  part:  "LEFT",  esp:  "IRSE/PARTIR"},
        {tipo:  "VI",  eng:  "FLEE",  past:  "FLED",  part:  "FLED",  esp:  "HUIR"},
        {tipo:  "VI",  eng:  "HURTS",  past:  "HURT",  part:  "HURT",  esp:  "DUELE"},
        {tipo:  "VI",  eng:  "MUST / OWE",  past:  "MUST / OWED",  part:  "MUST / OWED",  esp:  "DEBER"},
        {tipo:  "VI",  eng:  "LEAVE",  past:  "LEFT",  part:  "LEFT",  esp:  "DEJAR"},
        {tipo:  "VI",  eng:  "BLEED",  past:  "BLED",  part:  "BLED",  esp:  "DESANGRAR"},
        {tipo:  "VI",  eng:  "I AM",  past:  "WAS",  part:  "BEEN",  esp:  "ESTOY"},
        {tipo:  "VI",  eng:  "FIT",  past:  "FIT",  part:  "FIT",  esp:  "ENCAJAR"},
        {tipo:  "VI",  eng:  "RUN AGROUND",  past:  "RAN AGROUND",  part:  "RUN AGROUND",  esp:  "ENCALLAR"},
        {tipo:  "VI",  eng:  "GET UP",  past:  "GOT UP",  part:  "GOTTEN UP",  esp:  "LEVANTATE"},
        {tipo:  "VI",  eng:  "RIDE",  past:  "RODE",  part:  "RIDDEN",  esp:  "MONTAR"},
        {tipo:  "VI",  eng:  "DWELL",  past:  "DWELT",  part:  "DWELT",  esp:  "MORAR"},
        {tipo:  "VI",  eng:  "HIDE",  past:  "HID",  part:  "HIDDEN",  esp:  "OCULTAR"},
        {tipo:  "VI",  eng:  "HEAR",  past:  "HEARD",  part:  "HEARD",  esp:  "OIR"},
        {tipo:  "VI",  eng:  "BREAK",  past:  "BROKE",  part:  "BROKEN",  esp:  "QUEBRAR"},
        {tipo:  "VI",  eng:  "STING",  past:  "STUNG",  part:  "STUNG",  esp:  "PICAR"},
        {tipo:  "VI",  eng:  "BURST",  past:  "BURST",  part:  "BURST",  esp:  "REVENTAR"},
        {tipo:  "VI",  eng:  "LIE",  past:  "LAY",  part:  "LAIN",  esp:  "ACOSTAR"},
        {tipo:  "VI",  eng:  "BEAR",  past:  "BORE",  part:  "BORNE",  esp:  "SOPORTAR"},
    ],
    VI11: [

        {tipo:  "VI",  eng:  "SOW",  past:  "SOWED",  part:  "SOWN",  esp:  "SEMBRAR"},
        {tipo:  "VI",  eng:  "SHAKE",  past:  "SHOOK",  part:  "SHAKEN",  esp:  "TEMBLAR"},
        {tipo:  "VI",  eng:  "THROW",  past:  "THREW",  part:  "THROWN",  esp:  "TIRAR"},
        {tipo:  "VI",  eng:  "COST",  past:  "COST",  part:  "COST",  esp:  "VALER"},

    ]
};

window.verbosRegulares_VR ={

    VR1: [

        { tipo: "VR", eng: "COIN", esp: "ACUÑAR/ACUNAR" },
        { tipo: "VR", eng: "FACE", esp: "AFRONTAR" },
        { tipo: "VR", eng: "ADORE", esp: "ADORAR" },
        { tipo: "VR", eng: "COOL", esp: "ARRULLAR/ENFRIAR" },
        { tipo: "VR", eng: "ACCOMMODATE", esp: "ACOMODAR" },
        { tipo: "VR", eng: "DIE", esp: "AGONIZAR/MORIR" }, // DYING es el gerundio/estado
        { tipo: "VR", eng: "PUT UP WITH", esp: "AGUANTAR" },
        { tipo: "VR", eng: "ENDURE", esp: "AGUANTARSE" },
        { tipo: "VR", eng: "EMBRACE", esp: "ABRAZAR" },
        { tipo: "VR", eng: "BURN", esp: "ARDER" },
        { tipo: "VR", eng: "SEPARATE", esp: "APARTAR" },
        { tipo: "VR", eng: "RAISE", esp: "ALZAR" },
        { tipo: "VR", eng: "TURN OFF", esp: "APAGAR" },
        { tipo: "VR", eng: "DROWN", esp: "AHOGARSE" },
        { tipo: "VR", eng: "STAB", esp: "APUÑALAR" },
        { tipo: "VR", eng: "THREATEN", esp: "AMENAZAR" },
        { tipo: "VR", eng: "TIE", esp: "AMARRAR" },
        { tipo: "VR", eng: "CROSS", esp: "ATRAVESAR" },
        { tipo: "VR", eng: "DRAG", esp: "ARRASTRAR" },
        { tipo: "VR", eng: "NEED", esp: "NECESITAR" },
    ],
    VR2: [
        { tipo: "VR", eng: "START UP", esp: "ARRANCAR" },
        { tipo: "VR", eng: "SEARCH", esp: "BUSCAR" },
        { tipo: "VR",  eng: "LOAD", esp: "CARGAR" },
        { tipo: "VR",  eng: "NAIL", esp: "CLAVAR" },
        { tipo: "VR", eng: "CONQUEST", esp: "CONQUISTA" },
        { tipo: "VR",  eng: "CONFUSE", esp: "CONFUNDIR" },
        { tipo: "VR",  eng: "CRITICIZE", esp: "CRITICAR" },
        { tipo: "VR",  eng: "COMMAND", esp: "MANDAR" },
        { tipo: "VR",  eng: "COVER", esp: "CUBRIR" },
        { tipo: "VR",  eng: "WALK", esp: "CAMINAR" },
        { tipo: "VR",  eng: "YIELD", esp: "CEDER" },
        { tipo: "VR",  eng: "CONVERT", esp: "CONVERTIR" },
        { tipo: "VR",  eng: "CONDEMN", esp: "CONDENAR" },
        { tipo: "VR", eng: "WANT", esp: "QUERER" },
        { tipo: "VR", eng: "LOOK", esp: "MIRAR" },
        { tipo: "VR", eng: "USE", esp: "USAR" },
        { tipo: "VR", eng: "CALL", esp: "LLAMAR" },
        { tipo: "VR", eng: "INTEND", esp: "TENER LA INTENCIÓN" },
        { tipo: "VR", eng: "ASSIST", esp: "AYUDAR/ASISTIR" },
        { tipo: "VR", eng: "STAND", esp: "SOPORTAR/TOLERAR" },

    ],
    VR3: [

        { tipo: "VR", eng: "TRY", esp: "INTENTAR" },
        { tipo: "VR", eng: "ASK", esp: "PREGUNTAR" },
        { tipo: "VR", eng: "SEEM", esp: "PARECER" },
        { tipo: "VR", eng: "TALK", esp: "HABLAR" },
        { tipo: "VR", eng: "RETURN / COMEBACK", esp: "REGRESAR/VOLVER" },
        { tipo: "VR", eng: "START", esp: "COMENZAR" },
        { tipo: "VR", eng: "SHOW", esp: "MOSTRAR" },
        { tipo: "VR", eng: "PLAY", esp: "JUGAR" },
        { tipo: "VR", eng: "MOVE", esp: "MOVER" },
        { tipo: "VR", eng: "LIVE", esp: "VIVIR" },
        { tipo: "VR", eng: "BELIEVE", esp: "CREER" },
        { tipo: "VR", eng: "HAPPEN", esp: "SUCEDER" },
        { tipo: "VR",  eng: "SAVE", esp: "AHORRAR/SALVAR" },
        { tipo: "VR",  eng: "CARRY", esp: "CARGAR/LLEVAR" },
        { tipo: "VR",  eng: "WAIT", esp: "ESPERAR (LUGAR)" },
        { tipo: "VR",  eng: "HOPE", esp: "ESPERAR (DESEO)" },
        { tipo: "VR",  eng: "REMEMBER", esp: "RECORDAR" },
        { tipo: "VR",  eng: "FIX", esp: "REPARAR" },
        { tipo: "VR", eng: "OPEN", esp: "ABRIR" },
        { tipo: "VR", eng: "COOK", esp: "COCINAR" },
        
    ],
    VR4: [
        
        { tipo: "VR", eng: "WANDER", esp: "DEAMBULAR" },
        { tipo: "VR", eng: "RETRIEVE", esp: "RECUPERAR" },
        { tipo: "VR", eng: "SQUEEZE", esp: "EXPRIMIR" },
        { tipo: "VR", eng: "ACHIEVE", esp: "CONSEGUIR/LOGRAR" },
        { tipo: "VR", eng: "KILL", esp: "MATAR" },
        { tipo: "VR",  eng: "ANSWER", esp: "CONTESTAR" },
        { tipo: "VR",  eng: "TRAVEL", esp: "VIAJAR" },
        { tipo: "VR",  eng: "JUMP", esp: "SALTAR" },
        { tipo: "VR",  eng: "CLIMB", esp: "ESCALAR/SUBIR" },
        { tipo: "VR",  eng: "DANCE", esp: "BAILAR" },
        { tipo: "VR",  eng: "LAUGH", esp: "REÍR" },
        { tipo: "VR",  eng: "CRY", esp: "LLORAR" },
        { tipo: "VR",  eng: "SMILE", esp: "SONREÍR" },
        { tipo: "VR",  eng: "SHOUT", esp: "GRITAR" },
        { tipo: "VR",  eng: "WHISPER", esp: "SUSURRAR" },
        { tipo: "VR",  eng: "TOUCH", esp: "TOCAR" },
        { tipo: "VR",  eng: "PUSH", esp: "EMPUJAR" },
        { tipo: "VR",  eng: "PULL", esp: "TIRAR/JALAR" },
        { tipo: "VR", eng: "WATCH", esp: "MIRAR/OBSERVAR" },
        { tipo: "VR", eng: "CLEAN", esp: "LIMPIAR" },

    ],
    VR5: [
        { tipo: "VR", eng: "TAKE OFF", esp: "DESPEGAR" },
        { tipo: "VR", eng: "LAND", esp: "ATERRIZAR" },
        { tipo: "VR", eng: "GIVE UP", esp: "RENDIRSE" },
        { tipo: "VR", eng: "FIND OUT", esp: "AVERIGUAR" },
        { tipo: "VR", eng: "GO ON", esp: "CONTINUAR" },
        { tipo: "VR", eng: "LOOK FOR", esp: "BUSCAR (ALGO PERDIDO)" },
        { tipo: "VR", eng: "LOOK AFTER", esp: "CUIDAR A ALGUIEN" },
        { tipo: "VR", eng: "APPEAR", esp: "APARECER (DE REPENTE)" },
        { tipo: "VR", eng: "RUN OUT OF", esp: "QUEDARSE SIN (GASOLINA/TIEMPO)" },
        { tipo: "VR", eng: "GET ALONG", esp: "HACERSE AMIGO/LLEVARSE BIEN" },
        { tipo: "VR", eng: "PICK UP", esp: "RECOGER A ALGUIEN" },
        { tipo: "VR", eng: "GIVE BACK", esp: "DEVOLVER ALGO" },
        { tipo: "VR", eng: "PUT OFF", esp: "POSPONER" },
        { tipo: "VR", eng: "TRY ON", esp: "PROBARSE (ROPA)" },
        { tipo: "VR", eng: "LOWER", esp: "BAJAR (VOLUMEN)" },
        { tipo: "VR", eng: "COME BACK", esp: "REGRESAR" },
        { tipo: "VR", eng: "GROW UP", esp: "CRECER (MADURAR)" },
        { tipo: "VR", eng: "DISCOVER", esp: "DESCUBRIR" },
        { tipo: "VR", eng: "HANG OUT", esp: "SALIR CON AMIGOS" },
        {tipo:  "VR",  eng:  "NAVIGATE",  esp:  "NAVEGAR"},

    ],
    VR6: [
        { tipo: "VR", eng: "AGREE", esp: "ACORDAR/ESTAR DE ACUERDO" },
        { tipo: "VR", eng: "DISAGREE", esp: "DISCREPAR" },
        { tipo: "VR", eng: "DECIDE", esp: "DECIDIR" },
        { tipo: "VR", eng: "PROMISE", esp: "PROMETER" },
        { tipo: "VR", eng: "SUGGEST", esp: "SUGERIR" },
        { tipo: "VR", eng: "RECOMMEND", esp: "RECOMENDAR" },
        { tipo: "VR", eng: "ADMIT", esp: "ADMITIT" },
        { tipo: "VR", eng: "DENY", esp: "NEGAR" },
        { tipo: "VR", eng: "COMPLAIN", esp: "QUEJARSE" },
        { tipo: "VR", eng: "IMAGINE", esp: "IMAGINAR" },
        { tipo: "VR", eng: "SUPPOSE", esp: "SUPONER" },
        { tipo: "VR", eng: "GUESS", esp: "ADIVINAR" },
        { tipo: "VR", eng: "SMELL", esp: "OLER" },
        { tipo: "VR", eng: "TASTE", esp: "SABOREAR" },
        { tipo: "VR", eng: "SOUND", esp: "SONAR (RUIDO)" },
        { tipo: "VR", eng: "WISH", esp: "DESEAR" },
        { tipo: "VR", eng: "BELONG", esp: "PERTENECER" },
        { tipo: "VR", eng: "DEPEND", esp: "DEPENDER" },
        { tipo: "VR", eng: "LEARN", esp: "APRENDER" },
        { tipo: "VR", eng: "GRADUATE",  esp: "GRADUARSE" },

    ],
    VR7: [
        { tipo: "VR", eng: "SHUT",esp: "CERRAR (PUERTA/OJOS)" },
        { tipo: "VR", eng: "CLOSE", esp: "CERRAR (GENERAL)" },
        { tipo: "VR", eng: "LOCK", esp: "CERRAR CON LLAVE" },
        { tipo: "VR", eng: "CURE", esp: "CURAR" },
        { tipo: "VR", eng: "HURT", esp: "LASTIMAR" },
        { tipo: "VR", eng: "COUGH", esp: "TOSER" },
        { tipo: "VR", eng: "SNEEZE", esp: "ESTORNUDAR" },
        { tipo: "VR", eng: "BREATHE", esp: "RESPIRAR" },
        { tipo: "VR", eng: "HELP", esp: "AYUDA/AYUDAR" },
        { tipo: "VR", eng: "PRINT", esp: "IMPRIMIR" },
        { tipo: "VR", eng: "SEND", esp: "ENVIAR" },
        { tipo: "VR", eng: "RECEIVE", esp: "RECIBIR" },
        { tipo: "VR", eng: "CHARGE", esp: "CARGAR (BATERÍA)" },
        { tipo: "VR", eng: "DOWNLOAD", esp: "DESCARGAR (INTERNET)" },
        { tipo: "VR", eng: "DELETE", esp: "BORRAR" },
        { tipo: "VR", eng: "BAKE", esp: "COCINAR AL HORNO" },
        { tipo: "VR", eng: "BOIL", esp: "HERVIR" },
        { tipo: "VR", eng: "FRY", esp: "FREÍR" },
        { tipo: "VR", eng: "ATTEND", esp: "ASISTIR (IR A UN LUGAR)" },
        { tipo: "VR", eng: "LISTEN", esp: "ESCUCHAR" },
    ],
    VR8: [
        { tipo: "VR", eng: "ANALYZE", esp: "ANALIZAR" },
        { tipo: "VR", eng: "COMPARE", esp: "COMPARAR" },
        { tipo: "VR", eng: "DEVELOP", esp: "DESARROLLAR" },
        { tipo: "VR", eng: "IMPROVE", esp: "MEJORAR" },
        { tipo: "VR", eng: "CREATE", esp: "CREAR" },
        { tipo: "VR", eng: "DESTROY", esp: "DESTRUIR" },
        { tipo: "VR", eng: "ORGANIZE", esp: "ORGANIZAR" },
        { tipo: "VR", eng: "PREPARE", esp: "PREPARAR" },
        { tipo: "VR", eng: "SOLVE", esp: "RESOLVER" },
        { tipo: "VR", eng: "EXPLAIN", esp: "EXPLICAR" },
        { tipo: "VR", eng: "DESCRIBE", esp: "DESCRIBIR" },
        { tipo: "VR", eng: "FULFILL", esp: "CUMPLIR" },
        { tipo: "VR", eng: "AVOID", esp: "EVITAR" },
        { tipo: "VR", eng: "PROPOSE", esp: "PROPONER" },
        { tipo: "VR", eng: "SUPPORT", esp: "APOYAR" },
        { tipo: "VR", eng: "SHARE", esp: "COMPARTIR" },
        { tipo: "VR", eng: "COMPETE", esp: "COMPETIR" },
        { tipo: "VR", eng: "CELEBRATE", esp: "CELEBRAR" },
        {tipo:  "VR",  eng:  "ENCHANCE",  esp:  "MEJORAR/REALIZAR"},
        {tipo:  "VR",  eng:  "ADDRESS",  esp:  "ABORDAR/DIRIGIRSE A"},
        {tipo:  "VR",  eng:  "EXTINGUISH",  esp:  "EXTINGUIR"},

    ],
    VR9: [

        {tipo:  "VR",  eng:  "OPTIMIZE",  esp:  "OPTIMIZAR"},
        {tipo:  "VR",  eng:  "GUARANTEE",  esp:  "GARANTIZAR"},
        {tipo:  "VR",  eng:  "SLAP",  esp:  "ABOFETEAR"},
        {tipo:  "VR",  eng:  "SCRATCH",  esp:  "ARAÑAR / RASCAR"},
        {tipo:  "VR",  eng:  "STEP",  esp:  "PISAR"},
        {tipo:  "VR",  eng:  "MEASURE",  esp:  "MEDIR"},
        {tipo:  "VR",  eng:  "MIND",  esp:  "MENTE/IMPORTAR"},
        {tipo:  "VR",  eng:  "MARCH",  esp:  "MARCHAR"},
        {tipo:  "VR",  eng:  "BRAKE",  esp:  "FRENAR"},
        {tipo:  "VR",  eng:  "RESIST",  esp:  "RESISTIR"},
        {tipo:  "VR",  eng:  "STAIN",  esp:  "MANCHAR"},
        {tipo:  "VR",  eng:  "PERFORM",  esp:  "RENDIR"},
        {tipo:  "VR",  eng:  "REST",  esp:  "DESCANSAR"},
        {tipo:  "VR",  eng:  "DECANT",  esp:  "DECANTAR"},
        {tipo:  "VR",  eng:  "HARM",  esp:  "DAÑAR"},
        {tipo:  "VR",  eng:  "CONFRONT",  esp:  "ENFRENTAR"},
        {tipo:  "VR",  eng:  "WRAP",  esp:  "ENVOLVER"},
        {tipo:  "VR",  eng:  "FOG UP",  esp:  "EMPAÑAR"},
        {tipo:  "VR",  eng:  "ENRAGE",  esp:  "ENFURECER"},

    ],
    VR10: [

        {tipo:  "VR",  eng:  "DELIVER",  esp:  "ENTREGAR"},
        {tipo:  "VR",  eng:  "EMIGRATED",  esp:  "EMIGRÓ"},
        {tipo:  "VR",  eng:  "EXCITE",  esp:  "EXCITAR"},
        {tipo:  "VR",  eng:  "DIRTY",  esp:  "ENSUCIAR"},
        {tipo:  "VR",  eng:  "CHAIN",  esp:  "ENCADENAR"},
        {tipo:  "VR",  eng:  "DECEIVE",  esp:  "ENGAÑAR"},
        {tipo:  "VR",  eng:  "LOCK UP",  esp:  "ENCERRAR"},
        {tipo:  "VR",  eng:  "MISS / LACK",  esp:  "FALTAR"},
        {tipo:  "VR",  eng:  "FORCE",  esp:  "FORZAR / FUERZA"},
        {tipo:  "VR",  eng:  "FAIL",  esp:  "FALLAR"},
        {tipo:  "VR",  eng:  "FLOW",  esp:  "FLUIR"},
        {tipo:  "VR",  eng:  "ANNOY",  esp:  "FASTIDIAR"},
        {tipo:  "VR",  eng:  "GERMINATES",  esp:  "GERMINA"},
        {tipo:  "VR",  eng:  "HUMILIATE",  esp:  "HUMILLAR"},
        {tipo:  "VR",  eng:  "INHABITS",  esp:  "HABITA"},
        {tipo:  "VR",  eng:  "INHERITS",  esp:  "HEREDA"},
        {tipo:  "VR",  eng:  "IMPACT",  esp:  "IMPACTAR"},
        {tipo:  "VR",  eng:  "PREVENT",  esp:  "IMPIDAMOS"},
        {tipo:  "VR",  eng:  "ILLUMINATES",  esp:  "ILUMINA"},
        {tipo:  "VR",  eng:  "SACRIFICE",  esp:  "INMOLARSE"},

    ],
    VR11: [

        {tipo:  "VR",  eng:  "JUDGE",  esp:  "JUZGAR"},
        {tipo:  "VR",  eng:  "FILL",  esp:  "LLENAR"},
        {tipo:  "VR",  eng:  "BARK",  esp:  "LADRAR"},
        {tipo:  "VR",  eng:  "DESERVE",  esp:  "MERECER"},
        {tipo:  "VR",  eng:  "MIX",  esp:  "MEZCLAR"},
        {tipo:  "VR",  eng:  "MOVES",  esp:  "MUEVE"},
        {tipo:  "VR",  eng:  "BEG",  esp:  "MENDIGAR"},
        {tipo:  "VR",  eng:  "WANE",  esp:  "MENGUAR"},
        {tipo:  "VR",  eng:  "DARKEN",  esp:  "OSCURECER"},
        {tipo:  "VR",  eng:  "HATE",  esp:  "ODIAR"},
        {tipo:  "VR",  eng:  "ANOINT",  esp:  "UNGIR"},
        {tipo:  "VR",  eng:  "PLANT",  esp:  "PLANTAR"},
        {tipo:  "VR",  eng:  "PERSISTS",  esp:  "PERSISTE"},
        {tipo:  "VR",  eng:  "PROTECT",  esp:  "PROTEGER"},
        {tipo:  "VR",  eng:  "WEIGH / SORROW",  esp:  "PESAR"},
        {tipo:  "VR",  eng:  "REVEAL",  esp:  "REVELAR"},
        {tipo:  "VR",  eng:  "RECOGNIZE",  esp:  "RECONOCER"},
        {tipo:  "VR",  eng:  "RESONATE / ECHO",  esp:  "RESONAR"},
        {tipo:  "VR",  eng:  "RUMBLE / BOOM",  esp:  "RETUMBAR"},

    ],
    VR12: [

        {tipo:  "VR",  eng:  "RESURRECT / REVIVE",  esp:  "RESUCITAR"},
        {tipo:  "VR",  eng:  "OVERFLOW",  esp:  "REBOSAR"},
        {tipo:  "VR",  eng:  "PRAY",  esp:  "RESAR"},
        {tipo:  "VR",  eng:  "RECEDE",  esp:  "RETROCEDER"},
        {tipo:  "VR",  eng:  "SUFFER",  esp:  "SUFRIR"},
        {tipo:  "VR",  eng:  "FOLLOW",  esp:  "SEGUIR"},
        {tipo:  "VR",  eng:  "SERVE",  esp:  "SERVIR"},
        {tipo:  "VR",  eng:  "SWEAT",  esp:  "SUDOR"},
        {tipo:  "VR",  eng:  "SATIATE / QUENCH",  esp:  "SACIAR"},
        {tipo:  "VR",  eng:  "SEAL",  esp:  "SELLAR"},
        {tipo:  "VR",  eng:  "HEAL",  esp:  "SANAR"},
        {tipo:  "VR",  eng:  "TREMBLE",  esp:  "TIEMBLA"},
        {tipo:  "VR",  eng:  "TURN",  esp:  "DOBLAR / GIRAR"},
        {tipo:  "VR",  eng:  "TRAFFIC",  esp:  "TRAFICAR"},
        {tipo:  "VR",  eng:  "SWALLOW",  esp:  "TRAGAR"},
        {tipo:  "VR",  eng:  "TREAT / TRY",  esp:  "TRATAR"},
        
    ],
    VR13: [



    ]
};

window.sustantivos_S = {

    S1: [

        { tipo: "S",  eng: "WEAPON", esp: "ARMA" },
        { tipo: "S",  eng: "ABYSS", esp: "ABISMO" },
        { tipo: "S",  eng: "STEEL", esp: "ACERO" },
        { tipo: "S",  eng: "NEEDLES", esp: "AGUJAS" },
        { tipo: "S",  eng: "DISTRESS", esp: "AFLICCIÓN" },
        { tipo: "S",  eng: "SUFFOCATION", esp: "ASFIXIA" },
        { tipo: "S",  eng: "GREED", esp: "AVARICIA/CODICIA" },
        { tipo: "S",  eng: "SEAT", esp: "ASIENTO" },
        { tipo: "S",  eng: "SAND", esp: "ARENA" },
        { tipo: "S",  eng: "STILL", esp: "TODAVÍA" },
        { tipo: "S",  eng: "AMBITION", esp: "AMBICIÓN" },
        { tipo: "S",  eng: "SUNRISE", esp: "AMANECER" },
        { tipo: "S",  eng: "BREATH", esp: "ALIENTO" },
        { tipo: "S",  eng: "ANGUISH", esp: "ANGUSTIA" },
        { tipo: "S",  eng: "AIR", esp: "AIRE" },
        { tipo: "S",  eng: "CLAY", esp: "ARCILLA" },
        { tipo: "S",  eng: "FLAG", esp: "BANDERA" },
        { tipo: "S",  eng: "MUD", esp: "BARRO" },
        { tipo: "S",  eng: "ANTIDOTE", esp: "ANTÍDOTO" },
        { tipo: "S", eng: "PLUG", esp: "ENCHUFE" },
        
    ],
    S2: [
        { tipo: "S",  eng: "APATHY", esp: "APATÍA" },
        { tipo: "S",  eng: "BARRIER", esp: "BARRERA" },
        { tipo: "S",  eng: "BULLET", esp: "BALA" },
        { tipo: "S",  eng: "GOODNESS", esp: "BONDAD" },
        { tipo: "S",   eng: "CHAOS", esp: "CAOS" },
        { tipo: "S",   eng: "CLARITY", esp: "CLARIDAD" },
        { tipo: "S",   eng: "MEAT", esp: "CARNE" },
        { tipo: "S",   eng: "SKY", esp: "CIELO" },
        { tipo: "S",   eng: "EMBERS", esp: "BRASAS" },
        { tipo: "S",   eng: "BOAT", esp: "BARCO" },
        { tipo: "S",   eng: "FOOL", esp: "BOBO/NECIO" },
        { tipo: "S",   eng: "TRASH", esp: "BASURA" },
        { tipo: "S",   eng: "ARMOR", esp: "BLINDAJE/ARMADURA" },
        { tipo: "S",   eng: "BATTLE", esp: "BATALLA" },
        { tipo: "S",   eng: "CRYSTALS", esp: "CRISTALES" },
        { tipo: "S",   eng: "CHAINS", esp: "CADENAS" },
        { tipo: "S",   eng: "FREE FALL", esp: "CAÍDA LIBRE" },
        { tipo: "S",   eng: "COMBAT", esp: "COMBATE" },
        { tipo: "S",   eng: "ASHES", esp: "CENIZAS" },
        { tipo: "S",   eng: "CROOK", esp: "CAYADO" },
        
    ],
    S3: [
        { tipo: "S",   eng: "BOILER", esp: "CALDERA" },
        { tipo: "S",   eng: "REED", esp: "CAÑA" },
        { tipo: "S",   eng: "FIELD", esp: "CAMPO" },
        { tipo: "S",   eng: "FANGS", esp: "COLMILLOS" },
        { tipo: "S",   eng: "SPARK", esp: "CHISPA" },
        { tipo: "S",   eng: "CYCLE", esp: "CICLO" },
        { tipo: "S",   eng: "CODE", esp: "CÓDIGO" }, 
        { tipo: "S",   eng: "BOLT", esp: "CERROJO" },
        { tipo: "S",   eng: "LOCK", esp: "CERRADURA/CERRAR" },
        { tipo: "S",   eng: "VIRUS", esp: "VIRUS" },
        { tipo: "S",  eng: "PREDATOR", esp: "DEPREDADOR" },
        { tipo: "S",  eng: "TREASURE", esp: "TESORO" },
        { tipo: "S",  eng: "LETTER", esp: "CARTA/LETRA" },
        { tipo: "S",  eng: "SINS", esp: "PECADOS" },
        { tipo: "S",  eng: "MEADOWS", esp: "PRADERAS" },
        { tipo: "S",  eng: "GIFT", esp: "REGALO / DON" },
        { tipo: "S",  eng: "BREEZE", esp: "BRISA" },
        { tipo: "S",  eng: "MAMMALS", esp: "MAMÍFEROS" },
        { tipo: "S",  eng: "SELFISHNESS", esp: "EGOÍSMO" },
        { tipo: "S",  eng: "WOUND", esp: "HERIDA" },
    ],
    S4: [

        { tipo: "S",  eng: "PAIN", esp: "DOLOR" },
        { tipo: "S",  eng: "EMERGENCY", esp: "EMERGENCIA" },
        { tipo: "S",  eng: "DANGER", esp: "PELIGRO" }, 
        { tipo: "S",  eng: "BLOOD", esp: "SANGRE" },
        { tipo: "S",  eng: "BONE", esp: "HUESO" },
        { tipo: "S",  eng: "HEART", esp: "CORAZÓN" },
        { tipo: "S",  eng: "PILL", esp: "PASTILLA/PÍLDORA" },
        { tipo: "S", eng: "STORM", esp: "TORMENTA" },
        { tipo: "S", eng: "SNOW", esp: "NIEVE" },
        { tipo: "S", eng: "YEAR", esp: "AÑO" },
        { tipo: "S", eng: "FOG", esp: "NIEBLA" },
        { tipo: "S", eng: "LIGHTNING", esp: "RAYO / RELÁMPAGO" },
        { tipo: "S", eng: "WEEK", esp: "SEMANA" },
        { tipo: "S", eng: "MONTH", esp: "MES" },
        { tipo: "S", eng: "COMPUTER", esp: "COMPUTADORA" },
        { tipo: "S", eng: "KEYBOARD", esp: "TECLADO" },
        { tipo: "S", eng: "MOUSE", esp: "RATÓN (INFORMÁTICA)" },
        { tipo: "S", eng: "SCREEN", esp: "PANTALLA" },
        { tipo: "S", eng: "EMAIL", esp: "CORREO ELECTRÓNICO" },
        { tipo: "S", eng: "PASSWORD", esp: "CONTRASEÑA" }
        
    ],
    S5: [
        { tipo: "S", eng: "FILE", esp: "ARCHIVO" },
        { tipo: "S", eng: "FOLDER", esp: "CARPETA" },
        { tipo: "S", eng: "DESK", esp: "ESCRITORIO" },
        { tipo: "S", eng: "MEETING", esp: "REUNIÓN" },
        { tipo: "S", eng: "CALL", esp: "LLAMADA" },
        { tipo: "S", eng: "MESSAGE", esp: "MENSAJE" },
        { tipo: "S", eng: "HUNGRY", esp: "HAMBRE" },
        { tipo: "S", eng: "THIRST", esp: "SED" },
        { tipo: "S", eng: "BREAKFAST", esp: "DESAYUNO" },
        { tipo: "S", eng: "LUNCH", esp: "ALMUERZO" },
        { tipo: "S", eng: "DINNER", esp: "CENA" },
        { tipo: "S", eng: "KNIFE", esp: "CUCHILLO" },
        { tipo: "S", eng: "FORK", esp: "TENEDOR" },
        { tipo: "S", eng: "SPOON", esp: "CUCHARA" },
        { tipo: "S", eng: "PLATE", esp: "PLATO" },
        { tipo: "S", eng: "GLASS", esp: "VASO/VIDRIO/CRISTAL" },
        { tipo: "S", eng: "NAPKIN", esp: "SERVILLETA" },
        { tipo: "S", eng: "RECIPE", esp: "RECETA" },
        { tipo: "S", eng: "PARENTS", esp: "PADRES (MADRE Y PADRE)" },
        { tipo: "S", eng: "RELATIVES", esp: "PARIENTES/FAMILIARES" },
        
    ],
    S6:[
        { tipo: "S", eng: "STREET", esp: "CALLE" },
        { tipo: "S", eng: "BUILDING", esp: "EDIFICIO" },
        { tipo: "S", eng: "CITY HALL", esp: "AYUNTAMIENTO" },
        { tipo: "S", eng: "LIBRARY", esp: "BIBLIOTECA" },
        { tipo: "S", eng: "BOOKSTORE", esp: "LIBRERÍA (TIENDA)" },
        { tipo: "S", eng: "BAKERY", esp: "PANADERÍA" },
        { tipo: "S", eng: "PHARMACY", esp: "FARMACIA" },
        { tipo: "S", eng: "BARBER SHOP", esp: "BARBERÍA/PELUQUERÍA" },
        { tipo: "S", eng: "CINEMA", esp: "CINE" },
        { tipo: "S", eng: "PARK", esp: "PARQUE" },
        { tipo: "S", eng: "SQUARE", esp: "PLAZA" },
        { tipo: "S", eng: "STATION", esp: "ESTACIÓN" },
        { tipo: "S", eng: "AIRPORT", esp: "AEROPUERTO" },
        { tipo: "S", eng: "MUSEUM", esp: "MUSEO" },
        { tipo: "S", eng: "CHURCH", esp: "IGLESIA" },
        { tipo: "S", eng: "BRIDGE", esp: "PUENTE" },
        { tipo: "S", eng: "CORNER", esp: "ESQUINA" },
        { tipo: "S", eng: "SIDEWALK", esp: "ACERA" },
        { tipo: "S", eng: "TRAFFIC LIGHT", esp: "SEMÁFORO" },
        { tipo: "S", eng: "NEIGHBORHOOD", esp: "BARRIO" },
    ],
    S7:[
        { tipo: "S", eng: "SHIRT", esp: "CAMISA" },
        { tipo: "S", eng: "T-SHIRT", esp: "CAMISETA" },
        { tipo: "S", eng: "PANTS", esp: "PANTALONES" },
        { tipo: "S", eng: "SKIRT", esp: "FALDA" },
        { tipo: "S", eng: "DRESS", esp: "VESTIDO" },
        { tipo: "S", eng: "SOCKS", esp: "CALCETINES" },
        { tipo: "S", eng: "SHOES", esp: "ZAPATOS" },
        { tipo: "S", eng: "COAT", esp: "CHAQUETA/ABRIGO" },
        { tipo: "S", eng: "HAT", esp: "SOMBRERO/GORRA" },
        { tipo: "S", eng: "BELT", esp: "CINTURÓN" },
        { tipo: "S", eng: "GLOVES", esp: "GUANTES" },
        { tipo: "S", eng: "SCARF", esp: "BUFANDA" },
        { tipo: "S", eng: "TIE", esp: "CORBATA" },
        { tipo: "S", eng: "SUIT", esp: "TRAJE" },
        { tipo: "S", eng: "BAG", esp: "BOLSO/BOLSA" },
        { tipo: "S", eng: "POCKET", esp: "BOLSILLO" },
        { tipo: "S", eng: "WALLET", esp: "CARTERA" },
        { tipo: "S", eng: "WATCH", esp: "RELOJ DE PULSERA" },
        { tipo: "S", eng: "RING", esp: "ANILLO" },
        { tipo: "S", eng: "GLASSES", esp: "GAFAS" }  
    ],
    S8: [
        { tipo: "S", eng: "HEAD", esp: "CABEZA" },
        { tipo: "S", eng: "FACE", esp: "CARA" },
        { tipo: "S", eng: "EYE", esp: "OJO" },
        { tipo: "S", eng: "EAR", esp: "OÍDO/OREJA" },
        { tipo: "S", eng: "NOSE", esp: "NARIZ" },
        { tipo: "S", eng: "MOUTH", esp: "BOCA" },
        { tipo: "S", eng: "TEETH", esp: "DIENTES" },
        { tipo: "S", eng: "NECK", esp: "CUELLO" },
        { tipo: "S", eng: "SHOULDER", esp: "HOMBRO" },
        { tipo: "S", eng: "ARM", esp: "BRAZO" },
        { tipo: "S", eng: "HAND", esp: "MANO" },
        { tipo: "S", eng: "FINGER", esp: "DEDO (MANO)" },
        { tipo: "S", eng: "BACK", esp: "ESPALDA" },
        { tipo: "S", eng: "CHEST", esp: "PECHO" },
        { tipo: "S", eng: "STOMACH", esp: "ESTÓMAGO" },
        { tipo: "S", eng: "LEG", esp: "PIERNA" },
        { tipo: "S", eng: "KNEE", esp: "RODILLA" },
        { tipo: "S", eng: "FOOT", esp: "PIE" },
        { tipo: "S", eng: "TOE", esp: "DEDO (PIE)" },
        { tipo: "S", eng: "SKIN", esp: "PIEL" }
    ],
    S9: [
        { tipo: "S", eng: "HAMMER", esp: "MARTILLO" },
        { tipo: "S", eng: "NAIL", esp: "CLAVO" },
        { tipo: "S", eng: "SCREW", esp: "TORNILLO" },
        { tipo: "S", eng: "SCREWDRIVER", esp: "DESTORNILLADOR" },
        { tipo: "S", eng: "SAW", esp: "SIERRA" },
        { tipo: "S", eng: "DRILL", esp: "TALADRO" },
        { tipo: "S", eng: "TOOL", esp: "HERRAMIENTA" },
        { tipo: "S", eng: "WOOD", esp: "MADERA" },
        { tipo: "S", eng: "METAL", esp: "METAL" },
        { tipo: "S", eng: "STONE", esp: "PIEDRA" },
        { tipo: "S", eng: "BRICK", esp: "LADRILLO" },
        { tipo: "S", eng: "WALL", esp: "PARED/MURO" },
        { tipo: "S", eng: "ROOF", esp: "TECHO" },
        { tipo: "S", eng: "FLOOR", esp: "SUELO/PISO" },
        { tipo: "S", eng: "STAIRS", esp: "ESCALERAS" },
        { tipo: "S", eng: "PAINT", esp: "PINTURA" },
        { tipo: "S", eng: "BRUSH", esp: "PINCEL/BROCHA" },
        { tipo: "S", eng: "ROPE", esp: "CUERDA" },
        { tipo: "S", eng: "WIRE", esp: "ALAMBRE/CABLE" },
        {tipo: "S", eng: "PARTY", esp: "FIESTA"},
    ],
    S10: [
        { tipo: "S", eng: "SUITCASE", esp: "MALETA" },
        { tipo: "S", eng: "TICKET", esp: "BOLETO/ENTRADA" },
        { tipo: "S", eng: "PASSPORT", esp: "PASAPORTE" },
        { tipo: "S", eng: "TRIP", esp: "VIAJE" },
        { tipo: "S", eng: "RESERVATION", esp: "RESERVACIÓN" },
        { tipo: "S", eng: "LEFT", esp: "IZQUIERDA" },
        { tipo: "S", eng: "RIGHT", esp: "DERECHA" },
        { tipo: "S", eng: "STRAIGHT AHEAD", esp: "TODO RECTO" },
        { tipo: "S", eng: "MAP", esp: "MAPA" },
        { tipo: "S", eng: "DESTINATION", esp: "DESTINO" },
        { tipo: "S", eng: "PASSENGER", esp: "PASAJERO" },
        { tipo: "S", eng: "CUSTOMS", esp: "ADUANA" },
        { tipo: "S", eng: "BORDER", esp: "FRONTERA" },
        { tipo: "S", eng: "GUIDE", esp: "GUÍA" },
        { tipo: "S", eng: "HOLIDAY", esp: "VACACIONES" },
        { tipo: "S", eng: "ADVENTURE", esp: "AVENTURA" },
        { tipo: "S", eng: "FOREIGNER", esp: "EXTRANJERO" },
        { tipo: "S", eng: "TOURIST", esp: "TURISTA" },
        { tipo: "S", eng: "GUEST", esp: "INVITADO/HUÉSPED" },
        { tipo: "S", eng: "HOST", esp: "ANFITRIÓN" },
    ],
    S11: [
        { tipo: "S", eng: "MOUNTAIN", esp: "MONTAÑA" },
        { tipo: "S", eng: "RIVER", esp: "RÍO" },
        { tipo: "S", eng: "LAKE", esp: "LAGO" },
        { tipo: "S", eng: "FOREST", esp: "BOSQUE" },
        { tipo: "S", eng: "JUNGLE", esp: "SELVA" },
        { tipo: "S", eng: "DESERT", esp: "DESIERTO" },
        { tipo: "S", eng: "BEACH", esp: "PLAYA" },
        { tipo: "S", eng: "ISLAND", esp: "ISLA" },
        { tipo: "S", eng: "CAVE", esp: "CUEVA" },
        { tipo: "S", eng: "STAR", esp: "ESTRELLA" },
        { tipo: "S", eng: "MOON", esp: "LUNA" },
        { tipo: "S", eng: "SUN", esp: "SOL" },
        { tipo: "S", eng: "TREE", esp: "ÁRBOL" },
        { tipo: "S", eng: "FLOWER", esp: "FLOR" },
        { tipo: "S", eng: "GRASS", esp: "HIERBA/CÉSPED" },
        { tipo: "S", eng: "SEED", esp: "SEMILLA" },
        { tipo: "S", eng: "ROOT", esp: "RAÍZ" },
        { tipo: "S", eng: "LEAF", esp: "HOJA (PLANTA)" },
        { tipo: "S", eng: "GROUND", esp: "TIERRA/SUELO (NATURALEZA)" },
        {tipo: "S", eng: "MONEY", esp: "DINERO"},
    ],
    S12: [
        { tipo: "S", eng: "LAW", esp: "LEY" },
        { tipo: "S", eng: "JUDGE", esp: "JUEZ" },
        { tipo: "S", eng: "LAWYER", esp: "ABOGADO" },
        { tipo: "S", eng: "COURT", esp: "CORTE/TRIBUNAL" },
        { tipo: "S", eng: "PRISON", esp: "CÁRCEL" },
        { tipo: "S", eng: "CRIME", esp: "CRIMEN" },
        { tipo: "S", eng: "EVIDENCE", esp: "PRUEBA/EVIDENCIA" },
        { tipo: "S", eng: "PUNISHMENT", esp: "CASTIGO" },
        { tipo: "S", eng: "FINE", esp: "MULTA" },
        { tipo: "S", eng: "WITNESS", esp: "TESTIGO" },
        { tipo: "S", eng: "TRUTH", esp: "VERDAD" },
        { tipo: "S", eng: "LIE", esp: "MENTIRA" },
        { tipo: "S", eng: "SUCCESS", esp: "ÉXITO" },
        { tipo: "S", eng: "EXIT", esp: "SALIDA" },
        { tipo: "S", eng: "CARPET", esp: "ALFOMBRA" },
        { tipo: "S", eng: "WARNING", esp: "ADVERTENCIA" },
        { tipo: "S", eng: "ADVERTISEMENT", esp: "ANUNCIO/PUBLICIDAD" },
        { tipo: "S", eng: "FACTORY", esp: "FÁBRICA" },
        { tipo: "S", eng: "FABRIC", esp: "TELA" },
        { tipo: "S", eng: "FREEDOM", esp: "LIBERTAD" },
    ],
    
};
window.sustantivos_SS = {

    SS1: [
        { tipo: "S", eng: "THIEF", esp: "LADRÓN" },
        { tipo: "S", eng: "SUSPECT", esp: "SOSPECHOSO" },
        { tipo: "S", eng: "CLASSROOM", esp: "CLASE/AULA" },
        { tipo: "S", eng: "SUBJECT", esp: "ASIGNATURA/MATERIA" },
        { tipo: "S", eng: "HOMEWORK", esp: "TAREA" },
        { tipo: "S", eng: "TEST", esp: "EXAMEN" },
        { tipo: "S", eng: "GRADE", esp: "CALIFICACIÓN/NOTA" },
        { tipo: "S", eng: "DICTIONARY", esp: "DICCIONARIO" },
        { tipo: "S", eng: "PENCIL", esp: "LÁPIZ" },
        { tipo: "S", eng: "PEN", esp: "BOLÍGRAFO" },
        { tipo: "S", eng: "NOTEBOOK", esp: "CUADERNO" },
        { tipo: "S", eng: "ERASER", esp: "BORRADOR" },
        { tipo: "S", eng: "RULER", esp: "REGLA (MEDIR)" },
        { tipo: "S", eng: "BACKPACK", esp: "MOCHILA" },
        { tipo: "S", eng: "DEGREE", esp: "TÍTULO/DIPLOMA" },
        { tipo: "S", eng: "KNOWLEDGE", esp: "CONOCIMIENTO" },
        { tipo: "S", eng: "SKILL", esp: "HABILIDAD" },
        { tipo: "S", eng: "WORLD", esp: "MUNDO" },
        { tipo: "S", eng: "PEOPLE", esp: "GENTE" },
        { tipo: "S", eng: "POWER", esp: "PODER" },
    ],
    SS2: [

        {tipo: "S", eng: "GARDEN", esp: "JARDIN"},
        {tipo:  "S",  eng:  "SYSTEM",  esp:  "SISTEMA"},
        {tipo:  "S",  eng:  "INTERFACE",  esp:  "INTERFAZ"},
        {tipo:  "S",  eng:  "DECEPTION",  esp:  "ENGAÑO"},
        {tipo:  "S",  eng:  "CHEEK",  esp:  "MEJILLA"},
        {tipo:  "S",  eng:  "CLAW",  esp:  "GARRA"},
        {tipo:  "S",  eng:  "INNOCENCE",  esp:  "INOCENCIA"},
        {tipo:  "S",  eng:  "TOLL",  esp:  "PEAJE"},
        {tipo:  "S",  eng:  "FIEND",  esp:  "FANATICO/DEMONIO"},
        {tipo:  "S",  eng:  "RELIEF",  esp:  "ALIVIO"},
        {tipo:  "S",  eng:  "EVERYONE",  esp:  "TODOS"},
        {tipo:  "S",  eng:  "BRAKE",  esp:  "FRENO"},
        {tipo:  "S",  eng:  "MARCH / PARADE",  esp:  "MARCHA/DESFILE"},
        {tipo:  "S",  eng:  "FATHOMS",  esp:  "BRAZAS (MEDIDA)"},
        {tipo:  "S",  eng:  "BREASTSTROKE",  esp:  "BRAZA (NATACION)"},
        {tipo:  "S",  eng:  "GLANCE / LOOK",  esp:  "MIRADA"},
        {tipo:  "S",  eng:  "SOUL",  esp:  "ALMA"},
        {tipo:  "S",  eng:  "STAIN /SPOT",  esp:  "MANCHA"},
        {tipo:  "S",  eng:  "SOUND",  esp:  "SON (MUSICA)"},
        {tipo:  "S",  eng:  "DRUM",  esp:  "TAMBOR"},
    ],
    SS3: [
        
        {tipo:  "S",  eng:  "CRACK",  esp:  "GRIETA"},
        {tipo:  "S",  eng:  "RETAIL",  esp:  "COMERCIO"},
        {tipo:  "S",  eng:  "SMITHEREENS",  esp:  "AÑICOS"},
        {tipo:  "S",  eng:  "GLASS / CRYSTAL",  esp:  "CRISTAL"},
        {tipo:  "S",  eng:  "NEEDLE",  esp:  "AGUJA"},
        {tipo:  "S",  eng:  "ICE",  esp:  "HIELO"},
        {tipo:  "S",  eng:  "LIGHTHOUSE",  esp:  "FARO"},
        {tipo:  "S",  eng:  "REST",  esp:  "RESTO"},
        {tipo:  "S",  eng:  "OTHERS",  esp:  "DEMÁS"},
        {tipo:  "S",  eng:  "OWNER",  esp:  "DUEÑO"},
        {tipo:  "S",  eng:  "BREAK",  esp:  "DESCANSO"},
        {tipo:  "S",  eng:  "DISTRACTION",  esp:  "DISTRACCIÓN"},
        {tipo:  "S",  eng:  "MOURNING",  esp:  "DUELO"},
        {tipo:  "S",  eng:  "DOLPHIN",  esp:  "DELFÍN"},
        {tipo:  "S",  eng:  "CONTEMPT",  esp:  "DESPRECIO"},
        {tipo:  "S",  eng:  "DEFEAT",  esp:  "DERROTA"},
        {tipo:  "S",  eng:  "DYNAMITE",  esp:  "DINAMITA"},
        {tipo:  "S",  eng:  "EMPEROR",  esp:  "EMPERADOR"},
        {tipo:  "S",  eng:  "ENVY",  esp:  "ENVIDIA"},
        {tipo:  "S",  eng:  "HOPE",  esp:  "ESPERANZA"},

    ],
    SS4: [

        {tipo:  "S",  eng:  "MIRROR",  esp:  "ESPEJO"},
        {tipo:  "S",  eng:  "ECHO",  esp:  "ECO"},
        {tipo:  "S",  eng:  "SCHEME / OUTLINE",  esp:  "ESQUEMA"},
        {tipo:  "S",  eng:  "FRIGHT",  esp:  "ESPANTO"},
        {tipo:  "S",  eng:  "EGO",  esp:  "EGO"},
        {tipo:  "S",  eng:  "ARMY",  esp:  "EJERCITO"},
        {tipo:  "S",  eng:  "SWORD",  esp:  "ESPADA"},
        {tipo:  "S",  eng:  "FIRE",  esp:  "FUEGO"},
        {tipo:  "S",  eng:  "STRENGTH",  esp:  "FUERZA"},
        {tipo:  "S",  eng:  "INVOICE",  esp:  "FACTURA"},
        {tipo:  "S",  eng:  "PHASE",  esp:  "FASE"},
        {tipo:  "S",  eng:  "SOURCES",  esp:  "FUENTES"},
        {tipo:  "S",  eng:  "EDGE",  esp:  "FILO"},
        {tipo:  "S",  eng:  "GUARD",  esp:  "GUARDIA"},
        {tipo:  "S",  eng:  "DESIRE / WANT",  esp:  "GANAS"},
        {tipo:  "S",  eng:  "BLOWS / HITS",  esp:  "GOLPES"},
        {tipo:  "S",  eng:  "SEAGULL",  esp:  "GAVIOTA"},
        {tipo:  "S",  eng:  "SCREAM / CRY",  esp:  "GRITO"},
        {tipo:  "S",  eng:  "GASOLINE",  esp:  "GASOLINA"},
        {tipo:  "S",  eng:  "HORROR",  esp:  "HORROR"},

    ],
    SS5: [

        {tipo:  "S",  eng:  "BONFIRE",  esp:  "HOGUERA"},
        {tipo:  "S",  eng:  "FEATS",  esp:  "HAZAÑAS"},
        {tipo:  "S",  eng:  "HONOR",  esp:  "HONOR"},
        {tipo:  "S",  eng:  "EMPIRE",  esp:  "IMPERIO"},
        {tipo:  "S",  eng:  "HOME",  esp:  "HOGAR"},
        {tipo:  "S",  eng:  "WRATH / IRE",  esp:  "IRA"},
        {tipo:  "S",  eng:  "INTEREST",  esp:  "INTERÉS"},
        {tipo:  "S",  eng:  "INERTIA",  esp:  "INERCIA"},
        {tipo:  "S",  eng:  "OATH",  esp:  "JURAMENTO"},
        {tipo:  "S",  eng:  "PRODIGY",  esp:  "PRODIGIO"},
        {tipo:  "S",  eng:  "RAIN",  esp:  "LLUVIA"},
        {tipo:  "S",  eng:  "LAMENT / MOAN",  esp:  "LAMENTO"},
        {tipo:  "S",  eng:  "LEADER",  esp:  "LIDER"},
        {tipo:  "S",  eng:  "BED",  esp:  "LECHO"},
        {tipo:  "S",  eng:  "TEAR",  esp:  "LÁGRIMA"},
        {tipo:  "S",  eng:  "MESS",  esp:  "LIO"},
        {tipo:  "S",  eng:  "HALF",  esp:  "MITAD"},
        {tipo:  "S",  eng:  "MASTER",  esp:  "MAESTRO"},
        {tipo:  "S",  eng:  "MASSES",  esp:  "MASAS"},
        {tipo:  "S",  eng:  "WAY / MANNER",  esp:  "MANERA"},

    ],
    SS6: [

        {tipo:  "S",  eng:  "CURSE",  esp:  "MALDICIÓN"},
        {tipo:  "S",  eng:  "MARCH",  esp:  "MARCHA"},
        {tipo:  "S",  eng:  "BUTTERFLY",  esp:  "MARIPOSA"},
        {tipo:  "S",  eng:  "MERCY",  esp:  "MISERICORDIA"},
        {tipo:  "S",  eng:  "MANTLE / CLOAK",  esp:  "MANTO"},
        {tipo:  "S",  eng:  "MORAL",  esp:  "MORAL"},
        {tipo:  "S",  eng:  "DISCOMFORT",  esp:  "MALESTAR"},
        {tipo:  "S",  eng:  "EVIL / BAD",  esp:  "MAL"},
        {tipo:  "S",  eng:  "MIND",  esp:  "MENTE"},
        {tipo:  "S",  eng:  "GOAL",  esp:  "META"},
        {tipo:  "S",  eng:  "MARK / BRAND",  esp:  "MARCA"},
        {tipo:  "S",  eng:  "CLOUD",  esp:  "NUBE"},
        {tipo:  "S",  eng:  "PRAYER / SENTENCE",  esp:  "ORACIÓN"},
        {tipo:  "S",  eng:  "DARKNESS",  esp:  "OSCURIDAD"},
        {tipo:  "S",  eng:  "OBEDIENCE",  esp:  "OBEDIENCIA"},
        {tipo:  "S",  eng:  "WORKS / DEEDS",  esp:  "OBRAS"},
        {tipo:  "S",  eng:  "DEATH / DEMISE",  esp:  "OBITO"}, 
        {tipo:  "S",  eng:  "SHEEP",  esp:  "OVEJA"},
        {tipo:  "S",  eng:  "OBSTACLE",  esp:  "OBSTÁCULO"},
        {tipo:  "S",  eng:  "OXYGEN",  esp:  "OXIGENO"},
    ],
    SS7: [

        {tipo:  "S",  eng:  "UNION",  esp:  "UNIÓN"},
        {tipo:  "S",  eng:  "PULSE / WRIST",  esp:  "PULSO"},
        {tipo:  "S",  eng:  "PERMISSION / PERMIT",  esp:  "PERMISO"},
        {tipo:  "S",  eng:  "LUNGS",  esp:  "PULMONES"},
        {tipo:  "S",  eng:  "DEPARTURES",  esp:  "PARTIR (SALIR EJM BUS)"},
        {tipo:  "S",  eng:  "PAUSE",  esp:  "PAUSA"},
        {tipo:  "S",  eng:  "DOVE / PIGEON",  esp:  "PALOMA"},
        {tipo:  "S",  eng:  "PIECE",  esp:  "PEDAZO / TROZO"},
        {tipo:  "S",  eng:  "PALADIN / CHAMPION",  esp:  "PALADIN"},
        {tipo:  "S",  eng:  "BEARER / CARRIER",  esp:  "PORTADOR"},
        {tipo:  "S",  eng:  "PERFUME / SCENT",  esp:  "PERFUME"},
        {tipo:  "S",  eng:  "MEADOW / PRAIRIE",  esp:  "PRADERA"},
        {tipo:  "S",  eng:  "PASTOR / SHEPHERD",  esp:  "PASTOR"},
        {tipo:  "S",  eng:  "MERCY / PITY",  esp:  "PIEDAD"},
        {tipo:  "S",  eng:  "PAIR / EVEN",  esp:  "PAR"},
        {tipo:  "S",  eng:  "HURRY / RUSH",  esp:  "PRISA"},
        {tipo:  "S",  eng:  "WELL",  esp:  "POZO"},
        {tipo:  "S",  eng:  "PAPER / ROLE",  esp:  "PAPEL"},
        {tipo:  "S",  eng:  "WEIGHT",  esp:  "PESO"},
        {tipo:  "S",  eng:  "SOUND / RHYTHM",  esp:  "SON (MÚSICA)"},


    ],
    SS8: [

        {tipo:  "S",  eng:  "RIFLE",  esp:  "RIFLE"},
        {tipo:  "S",  eng:  "SCRAP",  esp:  "RETAL"},
        {tipo:  "S",  eng:  "REVOLUTION",  esp:  "REVOLUCIÓN"},
        {tipo:  "S",  eng:  "SCRATCHES",  esp:  "RASGUÑOS"},
        {tipo:  "S",  eng:  "ROCK",  esp:  "ROCA"},
        {tipo:  "S",  eng:  "ROAR",  esp:  "RUGIDO"},
        {tipo:  "S",  eng:  "FLOCK / HERD",  esp:  "REBAÑO"},
        {tipo:  "S",  eng:  "REFLECTION",  esp:  "REFLEJO"},
        {tipo:  "S",  eng:  "LAUGHTER",  esp:  "RISAS"},
        {tipo:  "S",  eng:  "BACKREST / SUPPORT",  esp:  "RESPALDO"},
        {tipo:  "S",  eng:  "REVERSE / BACKHAND",  esp:  "REVES"},
        {tipo:  "S",  eng:  "RAGE / RABIES",  esp:  "RABIA"},
        {tipo:  "S",  eng:  "PATH / PATHWAY",  esp:  "SENDA / SENDERO"},
        {tipo:  "S",  eng:  "LORD / SIR",  esp:  "SEÑOR"},
        {tipo:  "S",  eng:  "GROUND / FLOOR",  esp:  "SUELO"},
        {tipo:  "S",  eng:  "PRIDE / ARROGANCE",  esp:  "SOBERBIA"},
        {tipo:  "S",  eng:  "SENSATION",  esp:  "SENSACIÓN"},
        {tipo:  "S",  eng:  "EXCESS",  esp:  "SOBRA"},
        {tipo:  "S",  eng:  "SENSE / MEANING",  esp:  "SENTIDO"}, 
        {tipo:  "S",  eng:  "FOLLOWER",  esp:  "SEGUIDOR"},
        
    ],
    SS9: [

        {tipo:  "S",  eng:  "PRIEST",  esp:  "SACERDOTE"},
        {tipo:  "S",  eng:  "SUM / ADDITION",  esp:  "SUMA"},
        {tipo:  "S",  eng:  "SHADOW",  esp:  "SOMBRA"},
        {tipo:  "S",  eng:  "SIGN",  esp:  "SEÑAL"},
        {tipo:  "S",  eng:  "TAPESTRY",  esp:  "TAPIZ"},
        {tipo:  "S",  eng:  "TRENCHE",  esp:  "TRINCHERA"},
        {tipo:  "S",  eng:  "TYRANNY",  esp:  "TIRANÍA"},
        {tipo:  "S",  eng:  "THRONE",  esp:  "TRONO"},
        {tipo:  "S",  eng:  "TERRITORY",  esp:  "TERRITORIO"},
        {tipo:  "S",  eng:  "TRANSFORMATION",  esp:  "TRANSFORMACIÓN"},
        {tipo:  "S",  eng:  "TOXICITY",  esp:  "TOXICIDAD"},
        {tipo:  "S",  eng:  "THUNDER",  esp:  "TRUENO"},
        {tipo:  "S",  eng:  "VALUE / COURAGE",  esp:  "VALOR"},
        {tipo:  "S",  eng:  "WILL",  esp:  "VOLUNTAD"},
        {tipo:  "S",  eng:  "TIMES",  esp:  "VECES"},
        {tipo:  "S",  eng:  "LOBBY / HALL",  esp:  "VESTÍBULO"},
        {tipo:  "S",  eng:  "RODS / STICKS",  esp:  "VARA"},
        {tipo:  "S",  eng:  "POISON",  esp:  "VENENO"},
        {tipo:  "S",  eng:  "WIND",  esp:  "VIENTO"},
        {tipo:  "S",  eng:  "CANDLE / SAIL",  esp:  "VELA"},

    ],
    SS10: [

        
    ]
};
window.adjetivos_A = {

    A1: [
        { tipo: "A",  eng: "AROUND", esp: "ALREDEDOR" },
        { tipo: "A",  eng: "OUT", esp: "AFUERA" },
        { tipo: "A",  eng: "FORWARD", esp: "ADELANTE" },
        { tipo: "A",  eng: "ALTHOUGH", esp: "AUNQUE" },
        { tipo: "A",  eng: "EVEN", esp: "AÚN/INCLUSO" },
        { tipo: "A",  eng: "ABOVE", esp: "ARRIBA" },
        { tipo: "A",  eng: "HIGH", esp: "ALTO" },
        { tipo: "A",  eng: "WELL", esp: "BIEN" },
        { tipo: "A",  eng: "TIRED", esp: "CANSADO" },
        { tipo: "A",  eng: "BEAUTIFUL", esp: "BELLO" },
        { tipo: "A",  eng: "LIKE", esp: "COMO" },
        { tipo: "A",  eng: "ANY", esp: "CUALQUIER" },
        { tipo: "A",  eng: "AGAINST", esp: "CONTRA" },
        { tipo: "A",  eng: "CRUEL", esp: "CRUEL" },
        { tipo: "A",  eng: "DIZZY", esp: "MAREADO" },
        { tipo: "A", eng: "SICK", esp: "ENFERMO" },
        { tipo: "A", eng: "TASTY", esp: "SABROSO" },
        { tipo: "ADJ", eng: "SWEET", esp: "DULCE" },
        { tipo: "A", eng: "SMOOTH", esp: "SUAVE/LISO" },
        { tipo: "A", eng: "ROUGH", esp: "RUGOSO/ÁSPERO" },
     
    ],
    A2: [
    
        { tipo: "A", eng: "WEAK", esp: "DEBIL" },
        { tipo: "A", eng: "LIGHT", esp: "LIGERO" },
        { tipo: "A", eng: "WIDE", esp: "ANCHO" },
        { tipo: "A", eng: "DARK", esp: "OSCURO" },
        { tipo: "A", eng: "BRIGHT", esp: "BRILLANTE" },
        { tipo: "A", eng: "EXPENSIVE", esp: "CARO" },
        { tipo: "A", eng: "CHEAP", esp: "BARATO" },
        { tipo: "A", eng: "BRAVE", esp: "VALIENTE" },
        { tipo: "A", eng: "SMART", esp: "INTELIGENTE" },
        { tipo: "A", eng: "KIND", esp: "AMABLE" },
        { tipo: "A", eng: "RUDE", esp: "RUDO/GROSERO" },
        { tipo: "A", eng: "POLITE", esp: "EDUCADO" },
        { tipo: "A", eng: "EMPTY", esp: "VACÍO" },
        { tipo: "A", eng: "FULL", esp: "LLENO" },
        { tipo: "A", eng: "FAST", esp: "RÁPIDO" },
        { tipo: "A", eng: "SLOW", esp: "LENTO" },
        { tipo: "A", eng: "STRONG", esp: "FUERTE" },
        { tipo: "A", eng: "NARROW", esp: "ESTRECHO" },
        { tipo: "A", eng: "COWARD", esp: "COBARDE" },
        { tipo: "A", eng: "WILD", esp: "SALVAJE" },
    ],
    A3: [
        {tipo:  "A",  eng:  "EASY",  esp:  "FACIL"},
        {tipo:  "A",  eng:  "HUGE",  esp:  "ENORME"},
        {tipo:  "A",  eng:  "DIRTY",  esp:  "SUCIO"},
        {tipo:  "A",  eng:  "HARD",  esp:  "DURO"},
        {tipo:  "A",  eng:  "NEW",  esp:  "NUEVO"},
        {tipo:  "A",  eng:  "YOUNG",  esp:  "JOVEN"},
        {tipo:  "A",  eng:  "FLAT",  esp:  "LLANO"},
        {tipo:  "A",  eng:  "FOOLISH",  esp:  "TONTO"},
        {tipo:  "A",  eng:  "FREE",  esp:  "LIBRE"},
        {tipo:  "A",  eng:  "GENEROUS",  esp:  "GENEROSO"},
        {tipo:  "A",  eng:  "GOOD",  esp:  "BUENO"},
        {tipo:  "A",  eng:  "GREAT",  esp:  "ESTUPENDO"},
        {tipo:  "A",  eng:  "HANDSOME",  esp:  "ATRACTIVO"},
        {tipo:  "A",  eng:  "AMUSED",  esp:  "ENTRETENIDA"},
        {tipo:  "A",  eng:  "OUTRAGED",  esp:  "INDIGNADO"},
        {tipo:  "A",  eng:  "HUNGRY",  esp:  "HAMBRIENTO"},
        {tipo:  "A",  eng:  "LONG",  esp:  "LARGO"},
        {tipo:  "A",  eng:  "VIBRANT",  esp:  "VIBRANTE"},
        {tipo:  "A",  eng:  "PRAGMATIC",  esp:  "PRAGMÁTICO"},
        {tipo:  "A",  eng:  "DILIGENT",  esp:  "DILIGENTE"},
    ],
    A4: [
        { tipo: "A", eng: "SAFE", esp: "SEGURO" },
        { tipo: "A", eng: "SUNNY", esp: "SOLEADO" },
        { tipo: "A", eng: "CLOUDY", esp: "NUBLADO" },
        { tipo: "A", eng: "EARLY", esp: "TEMPRANO" },
        { tipo: "A", eng: "LATE", esp: "TARDE (TIEMPO)" },
        { tipo: "A", eng: "ALWAYS", esp: "SIEMPRE" },
        { tipo: "A", eng: "NEVER", esp: "NUNCA" },
        { tipo: "A", eng: "SOMETIMES", esp: "A VECES" },
        { tipo: "A", eng: "SOON", esp: "PRONTO" },
        { tipo: "A", eng: "TODAY", esp: "HOY" },
        { tipo: "A", eng: "TOMORROW", esp: "MAÑANA (DÍA)" },
        { tipo: "A", eng: "YESTERDAY", esp: "AYER" },
        { tipo: "A", eng: "HOT", esp: "CALOR/CALIENTE" },
        { tipo: "A", eng: "COLD", esp: "FRÍO" },
        { tipo: "A", eng: "SPICY", esp: "PICANTE" },
        { tipo: "A", eng: "SALTY", esp: "SALADO" },
        { tipo: "A", eng: "SOUR", esp: "AGRIO" },
        { tipo: "A", eng: "PREGNANT", esp: "EMBARAZADA" },
        { tipo: "A", eng: "EMBARRASSED", esp: "AVERGONZADO" },
        { tipo: "A", eng: "SANE", esp: "SANO (CUERDO)" },

    ],
    A5: [
        { tipo: "A", eng: "HAPPY", esp: "FELIZ" },
        { tipo: "A", eng: "SAD", esp: "TRISTE" },
        { tipo: "A", eng: "ANGRY", esp: "ENOJADO" },
        { tipo: "A", eng: "SCARED", esp: "ASUSTADO" },
        { tipo: "A", eng: "BORED", esp: "ABURRIDO" },
        { tipo: "A", eng: "EXCITED", esp: "EMOCIONADO" },
        { tipo: "A", eng: "SURPRISED", esp: "SORPRENDIDO" },
        { tipo: "A", eng: "NERVOUS", esp: "NERVIOSO" },
        { tipo: "A", eng: "SHY", esp: "TÍMIDO" },
        { tipo: "A", eng: "PROUD", esp: "ORGULLOSO" },
        { tipo: "A", eng: "JEALOUS", esp: "CELOSO" },
        { tipo: "A", eng: "WORRIED", esp: "PREOCUPADO" },
        { tipo: "A", eng: "CALM", esp: "TRANQUILO/CALMADO" },
        { tipo: "A", eng: "CURIOUS", esp: "CURIOSO" },
        { tipo: "A", eng: "GUILTY", esp: "CULPABLE" },
        { tipo: "A", eng: "INNOCENT", esp: "INOCENTE" },
        { tipo: "A", eng: "GRATEFUL", esp: "AGRADECIDO" },
        { tipo: "A", eng: "ANXIOUS", esp: "ANSIOSO" },
        { tipo: "A", eng: "CONFUSED", esp: "CONFUNDIDO" },
        { tipo: "A", eng: "SURE", esp: "SEGURO (CERTEZA)" },
    ],
    A6: [
        { tipo: "A", eng: "MUCH", esp: "MUCHO (INCONTABLE)" },
        { tipo: "A", eng: "MANY", esp: "MUCHOS (CONTABLE)" },
        { tipo: "A", eng: "LITTLE", esp: "POCO" },
        { tipo: "A", eng: "SOME", esp: "ALGUNOS" },
        { tipo: "A", eng: "NONE", esp: "NINGUNO" },
        { tipo: "A", eng: "ALL", esp: "TODO" },
        { tipo: "A", eng: "EACH", esp: "CADA" },
        { tipo: "A", eng: "TOO", esp: "DEMASIADO" },
        { tipo: "A", eng: "ENOUGH", esp: "SUFICIENTE/BASTA" },
        { tipo: "A", eng: "MORE", esp: "MÁS" },
        { tipo: "A", eng: "LESS", esp: "MENOS" },
        { tipo: "A", eng: "ALMOST", esp: "CASI" },
        { tipo: "A", eng: "ONLY", esp: "SÓLO/SOLAMENTE" },
        { tipo: "A", eng: "ALSO", esp: "TAMBIÉN" },
        { tipo: "A", eng: "NEITHER", esp: "TAMPOCO" },
        { tipo: "A", eng: "VERY", esp: "MUY" },
        { tipo: "A", eng: "SO", esp: "TAN (COMPARATIVO)" },
        { tipo: "A", eng: "MAYBE", esp: "QUIZÁS" },
        { tipo: "A", eng: "PROBABLY", esp: "PROBABLEMENTE" },
        { tipo: "A", eng: "REALLY", esp: "REALMENTE" },
    ],
    A7: [
        { tipo: "A", eng: "CURRENTLY", esp: "ACTUALMENTE" },
        { tipo: "A", eng: "ACTUALLY", esp: "EN REALIDAD" },
        { tipo: "A", eng: "HEALTHY", esp: "SALUDABLE (FÍSICO)" },
        { tipo: "A", eng: "FAIR", esp: "JUSTO" },
        { tipo: "A", eng: "UNFAIR", esp: "INJUSTO" },
        { tipo: "A", eng: "HEAVY", esp: "PESADO" },
        { tipo: "A", eng: "SHARP", esp: "AFILADO" },
        { tipo: "A", eng:  "PROACTIVE",  esp:  "PROACTIVO"},
        { tipo: "A", eng:  "EFFICIENT",  esp:  "EFICIENTE"},
        { tipo: "A", eng:  "COLLABORATIVE",  esp:  "COLABORATIVO"},
        { tipo: "A", eng:  "DEADLINEDRIVEN",  esp:  "ORIENTADO A PLAZOS"},
        { tipo: "A", eng:  "PUNCTUAL",  esp:  "PUNTUAL"},
        { tipo: "A", eng:  "RELIABLE",  esp:  "CONFIABLE"},
        { tipo: "A", eng:  "STREAMLINED",  esp:  "OPTIMIZADO/SIMPLIFICADO"},
        { tipo: "A", eng:  "METHODICAL",  esp:  "METÓDICO"},
        { tipo: "A", eng:  "SCALABLE",  esp:  "ESCALABLE"},
        { tipo: "A", eng:  "ACCOUNTABLE",  esp:  "RESPONSABLE/FIRME"},
        { tipo: "A", eng:  "ADAPTABLE",  esp:  "ADAPTABLE"},
        { tipo: "A", eng:  "DECISIVE",  esp:  "DECISIVO"},
        { tipo: "A", eng:  "METICULOUS",  esp:  "METICULOSO"},
        
    ],
    A8: [
        { tipo: "A", eng:  "EMPATHETIC",  esp:  "EMPÁTICO"},
        { tipo: "A", eng:  "INNOVATIVE",  esp:  "INNOVADOR"},
        {tipo:  "A",  eng:  "GLAD",  esp:  "CONTENTO / ALEGRE"},
        {tipo:  "A",  eng:  "BESIDE",  esp:  "AL LADO DE / JUNTO A"},
        {tipo:  "A",  eng:  "INSIGHFUL",  esp:  "PERSPICAZ/ESCLARECEDOR"},
        {tipo:  "A",  eng:  "CONCISE",  esp:  "CONCISO/BREVE"},
        {tipo:  "A",  eng:  "AUTONOMOUS",  esp:  "AUTÓNOMO"},
        {tipo:  "A",  eng:  "FUNCTIONAL",  esp:  "FUNCIONAL"},
        {tipo:  "A",  eng:  "HOPELESS",  esp:  "DESAHUCIADO"},
        {tipo:  "A",  eng:  "LATELY",  esp:  "ULTIMAMENTE"},
        {tipo:  "A",  eng:  "SACRED / HOLY",  esp:  "SAGRADO"},
        {tipo:  "A",  eng:  "ROTTEN",  esp:  "PODRIDO"},
        {tipo:  "A",  eng:  "WHOLE / ENTIRE",  esp:  "ENTERO"},
        {tipo:  "A",  eng:  "STANDING",  esp:  "DE PIE"},
        {tipo:  "A",  eng:  "TORN",  esp:  "DESGARRADA"},
        {tipo:  "A",  eng:  "DIFFICULT",  esp:  "DIFICIL"},
        {tipo:  "A",  eng:  "CLUELESS",  esp:  "DESPISTADO"},
        {tipo:  "A",  eng:  "DISGUISED",  esp:  "DISFRAZADO"},
        {tipo:  "A",  eng:  "ON / LIT",  esp:  "ENCENDIDO"},
        {tipo:  "A",  eng:  "STARRY",  esp:  "ESTRELLADO"},
        
    ],
    A9: [
        
        {tipo:  "A",  eng:  "UPRIGHT",  esp:  "ERGUIDO"},
        {tipo:  "A",  eng:  "ETERNAL",  esp:  "ETERNA"},
        {tipo:  "A",  eng:  "FLOWING",  esp:  "FLUYENDO"},
        {tipo:  "A",  eng:  "FIRM",  esp:  "FIRME"},
        {tipo:  "A",  eng:  "FAITHFUL",  esp:  "FIEL"},
        {tipo:  "A",  eng:  "FORGED",  esp:  "FORJADO"},
        {tipo:  "A",  eng:  "FED UP",  esp:  "HARTO"},
        {tipo:  "A",  eng:  "SUNKEN",  esp:  "HUNDIDO"},
        {tipo:  "A",  eng:  "IMPERIAL",  esp:  "IMPERIAL"},
        {tipo:  "A",  eng:  "INVINCIBLE",  esp:  "INVENCIBLE"},
        {tipo:  "A",  eng:  "INHIBITED",  esp:  "INHIBIDO"},
        {tipo:  "A",  eng:  "UNSHAKEABLE",  esp:  "INQUEBRANTABLE"},
        {tipo:  "A",  eng:  "FOOLISH / STUPID",  esp:  "NECIO"},
        {tipo:  "A",  eng:  "HARMFUL / NOXIOUS",  esp:  "NOCIVO"},
        {tipo:  "A",  eng:  "DEEP",  esp:  "PROFUNDO"},
        {tipo:  "A",  eng:  "PROSTRATE / BEDRIDDEN",  esp:  "POSTRAR"},
        {tipo:  "A",  eng:  "OWN",  esp:  "PROPIO"},
        {tipo:  "A",  eng:  "BORROWED",  esp:  "PRESTADO"},
        {tipo:  "A",  eng:  "TWISTED",  esp:  "RETORCIDO"},
        {tipo:  "A",  eng:  "LONELY /SOLITARY",  esp:  "SOLITARIO"},
        
    ],
    A10: [

        {tipo:  "A",  eng:  "LOOSE",  esp:  "SUELTO"},
        {tipo:  "A",  eng:  "SINCERE",  esp:  "SINCERO"},
        {tipo:  "A",  eng:  "ALONE",  esp:  "SOLO (SIN NADIE)"},
        {tipo:  "A",  eng:  "SUICIDAL / SUICIDE",  esp:  "SUICIDA"},
        {tipo:  "A",  eng:  "SYMBOLIC",  esp:  "SIMBÓLICO"},
        {tipo:  "A",  eng:  "CLUMSY / AWKWARD",  esp:  "TORPE"},
        {tipo:  "A",  eng:  "TENSE",  esp:  "TENSO"},
        {tipo:  "A",  eng:  "TENUOUS / FAINT",  esp:  "TENUE"},
        {tipo:  "A",  eng:  "CALM / QUIET",  esp:  "TRANQUILA"},
        {tipo:  "A",  eng:  "TOXIC",  esp:  "TÓXICO"},
        {tipo:  "A",  eng:  "TEMPERATE / MILD",  esp:  "TEMPLADO"},
        {tipo:  "A",  eng:  "SEVERAL / VARIOUS",  esp:  "VARIOS"},


    ]
};

window.lenguajeInformal_LI = {

    LI1: [
        
        { tipo: "LI", eng: "BUCK", esp: "UN DÓLAR" },
        { tipo: "LI", eng: "CASH", esp: "DINERO EN EFECTIVO" },
        { tipo: "LI", eng: "KID", esp: "NIÑO/CHAVAL" },
        { tipo: "LI", eng: "MATE", esp: "AMIGO/COMPAÑERO" },
        { tipo: "LI", eng: "GUY", esp: "TIPO/CHICO" },
        { tipo: "LI", eng: "STUFF", esp: "COSAS/COSA" },
        { tipo: "LI", eng: "AWESOME", esp: "ASOMBROSO/GENIAL" },
        { tipo: "LI", eng: "COOL", esp: "GENIAL/GUAY" },
        { tipo: "LI", eng: "MY BAD", esp: "ERROR MÍO" },
        { tipo: "LI", eng: "NO WORRIES", esp: "NO HAY PROBLEMA" },
        { tipo: "LI", eng: "BRO", esp: "HERMANO/COLEGA" },
        { tipo: "LI", eng: "CHILL", esp: "RELAJADO/TRANQUILO" },
        { tipo: "LI", eng: "GOAT", esp: "EL MEJOR DE TODOS LOS TIEMPOS" },
        { tipo: "LI", eng: "SHADY", esp: "SOSPECHOSO" },
        { tipo: "LI", eng: "BUMMER", esp: "DECEPCIÓN/FASTIDIO" },
        { tipo: "LI", eng: "CRIB", esp: "CASA/CHOZA" },
        { tipo: "LI", eng: "HYPE", esp: "ENTUSIASMO EXAGERADO" },
        { tipo: "LI", eng: "DOPE", esp: "GENIAL/EXCELENTE" },
        { tipo: "LI", eng: "YOLO", esp: "SOLO SE VIVE UNA VEZ" },
        { tipo: "LI", eng: "NO CAP", esp: "SIN MENTIRAS / DE VERDAD" },
    ],
    LI2: [
        
        { tipo: "LI", eng: "BANGER", esp: "ALGO EXCELENTE (MÚSICA O COMIDA)" },
        { tipo: "LI", eng: "GHOST", esp: "IGNORAR A ALGUIEN (DESAPARECER)" },
        { tipo: "LI", eng: "FLEX", esp: "PRESUMIR / ALARDEAR" },
        { tipo: "LI", eng: "TEA", esp: "CHISME / COTILLEO" },
        { tipo: "LI", eng: "BASIC", esp: "ALGUIEN SIN ORIGINALIDAD / COMÚN" },
        { tipo: "LI", eng: "WOKE", esp: "CONSCIENTE DE PROBLEMAS SOCIALES" },
        { tipo: "LI", eng: "LIT", esp: "MUY DIVERTIDO / ENCENDIDO" },
        { tipo: "LI", eng: "SAVAGE", esp: "ALGUIEN SIN FILTRO / VALIENTE" },
        { tipo: "LI", eng: "STAN", esp: "SER FAN MUY OBSESIONADO" },
        { tipo: "LI", eng: "FIRE", esp: "ESTÁ INCREÍBLE / FUEGO" },
        { tipo: "LI", eng: "SHOOK", esp: "IMPACTADO / SORPRENDIDO" },
        { tipo: "LI", eng: "SAY LESS", esp: "DIME MENOS / TE ENTENDÍ PERFECTO" },
        { tipo: "LI", eng: "MAIN CHARACTER", esp: "ALGUIEN QUE LLAMA LA ATENCIÓN" },
        { tipo: "LI", eng: "SIDE EYE", esp: "MIRADA DE JUZGAR O DESCONFIANZA" },
        { tipo: "LI", eng: "BFF", esp: "MEJOR AMIGO/A POR SIEMPRE" },
        { tipo: "LI", eng: "FOR REAL", esp: "DE VERDAD / EN SERIO" },
        { tipo: "LI", eng: "GUCCI", esp: "ESTÁ BIEN / TODO BIEN" },
        { tipo: "LI", eng: "RIRI", esp: "ALGUIEN MUY ATRACTIVO" },
        { tipo: "LI", eng: "SLAY", esp: "HACER ALGO EXCELENTE / ARRASAR" },
        { tipo: "LI", eng: "BULLSHIT", esp: "TONTERÍAS / MENTIRAS" },
    ],
    LI3: [
        
        { tipo: "LI", eng: "W", esp: "UNA VICTORIA / ALGO BUENO" },
        { tipo: "LI", eng: "L", esp: "UNA PERDICIÓN / UN FRACASO" },
        { tipo: "LI", eng: "LEGIT", esp: "VERDADERO / AUTÉNTICO" },
        { tipo: "LI", eng: "WILDIN", esp: "ACTUAR DE FORMA LOCA" },
        { tipo: "LI", eng: "CHILLAX", esp: "RELAJARSE TOTALMENTE" },
        { tipo: "LI", eng: "BIG MAD", esp: "MUY ENOJADO" },
        { tipo: "LI", eng: "SICK", esp: "INCREÍBLE / ASOMBROSO" },
        { tipo: "LI", eng: "MESSY", esp: "ALGUIEN QUE BUSCA DRAMA" },
        { tipo: "LI", eng: "GO OFF", esp: "DESAHOGARSE / HABLAR CON TODO" },
        { tipo: "LI", eng: "FIT", esp: "EL ATUENDO / LA ROPA" },
        { tipo: "LI", eng: "RENT FREE", esp: "OBSESIONADO CON ALGO/ALGUIEN" },
        { tipo: "LI", eng: "VIBES", esp: "BUENA VIBRA / ENERGÍA" },
        { tipo: "LI", eng: "BETS", esp: "ACEPTO EL RETO" },
        { tipo: "LI", eng: "FINNA", esp: "ESTOY A PUNTO DE" },
        {tipo:  "LI",  eng:  "SOME",  esp:  "UNOS / ALGUNOS"},
        {tipo:  "LI",  eng:  "WHILE",  esp:  "MIENTRAS"},
        {tipo:  "LI",  eng:  "ONLY",  esp:  "SOLO (SOLAMENTE)"},
    ],
    
};

window.lenguajeFormal_LF = {

    LF1: [
        { tipo: "LF", eng: "PIECE OF CAKE", esp: "ALGO MUY FÁCIL" },
        { tipo: "LF", eng: "UNDER THE WEATHER", esp: "SENTIRSE ENFERMO" },
        { tipo: "LF", eng: "BREAK A LEG", esp: "BUENA SUERTE" },
        { tipo: "LF", eng: "ONCE IN A BLUE MOON", esp: "CASI NUNCA" },
        { tipo: "LF", eng: "COST AN ARM AND A LEG", esp: "SER MUY CARO" },
        { tipo: "LF", eng: "LET THE CAT OUT OF THE BAG", esp: "REVELAR UN SECRETO" },
        { tipo: "LF", eng: "HIT THE SACK", esp: "IRSE A DORMIR" },
        { tipo: "LF", eng: "BEAT AROUND THE BUSH", esp: "ANDARSE CON RODEOS" },
        { tipo: "LF", eng: "BITE THE BULLET", esp: "AGUANTAR UNA SITUACIÓN" },
        { tipo: "LF", eng: "CUT TO THE CHASE", esp: "IR DIRECTO AL GRANO" },
        { tipo: "LF", eng: "CALL IT A DAY", esp: "TERMINAR EL TRABAJO" },
        { tipo: "LF", eng: "NO PAIN, NO GAIN", esp: "SIN ESFUERZO NO HAY PREMIO" },
        { tipo: "LF", eng: "SO FAR, SO GOOD", esp: "POR AHORA TODO BIEN" },
        { tipo: "LF", eng: "FURTHERMORE", esp: "ADEMÁS / ES MÁS" },
        { tipo: "LF", eng: "NOTWITHSTANDING", esp: "A PESAR DE / NO OBSTANTE" },
        { tipo: "LF", eng: "HOWEVER", esp: "SIN EMBARGO" },
        { tipo: "LF", eng: "REGARDING", esp: "CON RESPECTO A" },
        { tipo: "LF", eng: "CONSEQUENTLY", esp: "POR CONSIGUIENTE" },
        { tipo: "LF", eng: "TO SUMMARIZE", esp: "PARA RESUMIR" },
        { tipo: "LF", eng: "IN ACCORDANCE WITH", esp: "DE ACUERDO CON" },
    ],
    LF2: [
        { tipo: "LF", eng: "MOREOVER", esp: "ADEMÁS" },
        { tipo: "LF", eng: "THUS", esp: "POR LO TANTO / ASÍ" },
        { tipo: "LF", eng: "NEVERTHELESS", esp: "SIN EMBARGO / NO OBSTANTE" },
        { tipo: "LF", eng: "THEREFORE", esp: "POR CONSIGUIENTE" },
        { tipo: "LF", eng: "HENCE", esp: "DE AHÍ QUE / POR TANTO" },
        { tipo: "LF", eng: "SUBSEQUENTLY", esp: "POSTERIORMENTE" },
        { tipo: "LF", eng: "NAMELY", esp: "A SABER / ES DECIR" },
        { tipo: "LF", eng: "IN VIEW OF", esp: "EN VISTA DE" },
        { tipo: "LF", eng: "DUE TO", esp: "DEBIDO A" },
        { tipo: "LF", eng: "DESPITE", esp: "A PESAR DE" },
        { tipo: "LF", eng: "IN ORDER TO", esp: "CON EL FIN DE" },
        { tipo: "LF", eng: "PROVIDED THAT", esp: "SIEMPRE QUE / CON TAL QUE" },
        { tipo: "LF", eng: "WITH REGARD TO", esp: "CON RESPECTO A" },
        { tipo: "LF", eng: "NONETHELESS", esp: "A PESAR DE ESO" },
        { tipo: "LF", eng: "CONCERNING", esp: "ACERCA DE / RESPECTO A/EN RELACION CON" },
        { tipo: "LF", eng: "HENCEFORTH", esp: "DE AQUÍ EN ADELANTE" },
        { tipo: "LF", eng: "WHEREAS", esp: "MIENTRAS QUE" },
        { tipo: "LF", eng: "ACCORDINGLY", esp: "EN CONSECUENCIA" },
        { tipo: "LF", eng: "NOTABLY", esp: "PARTICULARMENTE / NOTABLEMENTE" },
        { tipo: "LF", eng: "WHENCE", esp: "DE DONDE" },
    ],
    LF3: [
        { tipo: "LF", eng: "FOR INSTANCE", past: "FOR INSTANCE", part: "FOR INSTANCE", esp: "POR EJEMPLO" },
        { tipo: "LF", eng: "IN ADDITION", past: "IN ADDITION", part: "IN ADDITION", esp: "ADEMÁS / ADICIONALMENTE" },
        { tipo: "LF", eng: "ON THE CONTRARY", past: "ON THE CONTRARY", part: "ON THE CONTRARY", esp: "AL CONTRARIO" },
        { tipo: "LF", eng: "MEANWHILE", past: "MEANWHILE", part: "MEANWHILE", esp: "MIENTRAS TANTO" },
        { tipo: "LF", eng: "CONVERSLY", past: "CONVERSLY", part: "CONVERSLY", esp: "POR EL CONTRARIO / A LA INVERSA" },
        { tipo: "LF", eng: "LIKEWISE", past: "LIKEWISE", part: "LIKEWISE", esp: "ASIMISMO / IGUALMENTE" },
        { tipo: "LF", eng: "IN THE EVENT OF", past: "IN THE EVENT OF", part: "IN THE EVENT OF", esp: "EN CASO DE" },
        { tipo: "LF", eng: "ON BEHALF OF", past: "ON BEHALF OF", part: "ON BEHALF OF", esp: "EN NOMBRE DE" },
        { tipo: "LF", eng: "PRIOR TO", past: "PRIOR TO", part: "PRIOR TO", esp: "ANTES DE / PREVIO A" },
        { tipo: "LF", eng: "AS REGARDS", past: "AS REGARDS", part: "AS REGARDS", esp: "EN LO QUE RESPECTA A" },
        { tipo: "LF", eng: "TO THAT END", past: "TO THAT END", part: "TO THAT END", esp: "CON ESE FIN" },
        { tipo: "LF", eng: "BY VIRTUE OF", past: "BY VIRTUE OF", part: "BY VIRTUE OF", esp: "EN VIRTUD DE" },
        { tipo: "LF", eng: "IN THE LIGHT OF", past: "IN THE LIGHT OF", part: "IN THE LIGHT OF", esp: "A LA LUZ DE / DADO QUE" },
        { tipo: "LF", eng: "WHEREBY", past: "WHEREBY", part: "WHEREBY", esp: "POR EL CUAL / A TRAVÉS DEL CUAL" },
        { tipo: "LF", eng: "FURTHER", past: "FURTHER", part: "FURTHER", esp: "MÁS ADELANTE / ADEMÁS" },
        { tipo: "LF", eng: "TO ELABORATE", past: "TO ELABORATE", part: "TO ELABORATE", esp: "PARA EXPLICAR EN DETALLE" },
        {tipo:  "LF",  eng:  "HOW DO YOU DO?",  esp:  "COMO ESTA USTED"},
        {tipo:  "LF",  eng:  "IT´S A PLEASURE TO MEET YOU",  esp:  "UN PLACER CONOCERLE"},
        {tipo:  "LF",  eng:  "TO WHOM IT MAY CONCERN",  esp:  "A QUIEN CORRESPONDA"},
        {tipo:  "LF",  eng:  "BEST REGARDS",  esp:  "SALUDOS CORDIALES"},
    ],
    LF4:[
        
        {tipo:  "LF",  eng:  "WE'LL STILL HAVE EACH OTHER",  esp:  "TODAVIA NOS TENDREMOS EL UNO AL OTRO"},
        {tipo:  "LF",  eng:  "NOTHING'S GONNA STOP US NOW",  esp:  "NADA NOS VA A DETENER AHORA"},
        {tipo:  "LF",  eng:  "WHATEVER IT TAKES",  esp:  "CUESTE LO QUE CUESTE"},
        {tipo:  "LF",  eng:  "STANDING STRONG FOREVER",  esp:  "MANTENIENDONOS FUERTES PARA SIEMPRE"},
        {tipo:  "LF",  eng:  "BEHIND",  esp:  "DETRÁS"}, 
        {tipo:  "LF",  eng:  "TOWARDS",  esp:  "HACIA"},
        {tipo:  "LF",  eng:  "JUSTLY",  esp:  "JUSTAMENTE"},
        {tipo:  "LF",  eng:  "BREAK FREE",  esp:  "LIBERARSE"},
        {tipo:  "LF",  eng:  "IN THE MIDDLE OF",  esp:  "EN MEDIO DE"},
        {tipo:  "LF",  eng:  "SEES ME",  esp:  "ME VE"},
        {tipo:  "LF",  eng:  "QUICK FUSE",  esp:  "MECHA RÁPIDA"},
        {tipo:  "LF",  eng:  "I DON'T CARE",  esp:  "ME DA IGUAL"},
        {tipo:  "LF",  eng:  "BE WORTH",  esp:  "VALER / MERECER LA PENA"},

    ],
};

